<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Tue, 11 Jun 2013 11:11:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['globalTemplate'] = array('showingapp','applications','didfirstappnow','navigationlink','closenavigationlink','forsuredidfirstnav','navigation','didfirstappnowbottom','navigationlink','closenavigationlink','forsuredidfirstnavbottom','navigationbottom','isCoreRC','hideRcForPerms','fbcenabled','isLargeTouch','isSmallTouch','showacplink','rclink','accessreports','notifications','messengerlink','notifications','showInboxNotify','ipsconnectRevalidateUrl','authenticating','updateTwitter','updateFacebook','update','canUpdateStatus','userLikeLink','nobbyNoMates','bloglink','pmLink','gallerylink','nexuslink','limFacebook','limTwitter','limWindows','memberbox','brandingBar','canSearch','showQuickNav','viewnewcontentapp','showhomeurl','applicationsloop','hasCustomPrimaryNavigation','didfirstnav','switchnavigation','countnav','hasHeaderAd','mainpageContent','hasFooterAd','didfirstnavbottom','switchnavigationbottom','countnavbottom','privvy','ruleslink','siterulestitletitle','siterulestitle','privvyMiddot','siteruleslink','isTouchDevice','skinchangerInner','uagentlocked','skinchangerOuter','langchooser','markRead','lastvisit','isfloat','sqldebuglink','closesqldebuglink','showdebuglevel','includeLightboxDoReal','vigLinkEnabled','fbcenabled','pagenumberintitle','brandingBar','memberbox','notifications','messengerlink','notificationsCount','notificationsLink','hasMemberList','hasForums','hasBlog','hasGallery','hasNexus','viewnewcontentapp','mainpageContent','skinchanger','langchooser','vigLinkEnabled');
$this->_funcHooks['includeCSS'] = array('donotminifycss','cssImport','cssInline','minifycss','csstominify','hasimportcss','inlinecss','donotminifycss','cssImport','cssInline','minifycss','csstominify','hasimportcss','inlinecss');
$this->_funcHooks['includeFeeds'] = array('dhjavascript','dhcss','dhrsd','dhraw','documentHeadItems','headitemsType','hasdocheaditems','dhjavascript','dhcss','dhrsd','dhraw','documentHeadItems','headitemsType','hasdocheaditems');
$this->_funcHooks['includeJS'] = array('usehttpsprototype','usehttpsscriptaculous','remoteloadjs','hasjsmodules','nmusehttpsp','nominifyremoteloadjs','nmusehttpss','nominifyremoteloadjs2','minifyjs','isLargeTouch','minifyjs');
$this->_funcHooks['includeMeta'] = array('ogCaveman','hasIdentifier','hasDescription','metaTagsInner','metaTags','metatags','ogCaveman','hasIdentifier','hasDescription','metaTagsInner','metaTags','metatags');
$this->_funcHooks['includeRTL'] = array('isrtl','checkrtl','langData','importrtlcss','importrtlcss','importrtlcss','importrtlcss','RTLMargin','hasMemberTopicMax','isrtl','checkrtl','langData','importrtlcss','importrtlcss','importrtlcss','importrtlcss');
$this->_funcHooks['includeVars'] = array('hasFBCHash','istm','istl','canswfupload','usefurl','hasNotification','autodst');
$this->_funcHooks['inlineLogin'] = array('extrafields','facebook','twitterBox','haswindowslive','extraform','registerServices','anonymous','privvy','hasReplacement');
$this->_funcHooks['liveEditJs'] = array('hasSkinData','liveEditOn');
$this->_funcHooks['nextPreviousTemplate'] = array('useAjaxPrev','prevpage','useAjaxNext','nextpage','haspages','useAjaxPrev','prevpage','useAjaxNext','nextpage','haspages');
$this->_funcHooks['paginationTemplate'] = array('hasRealTitle','hasRealTitle','hasPage','activepage','pagination','hasRealTitleFirst','firstpage','hasRealTitlePrev','prevpage','furlinfo','normalpages','hasRealTitleNext','nextpage','hasRealTitleLast','lastpage','notDisableSinglePage','haspages','prevpage','nextpage','haspages');
$this->_funcHooks['quickSearch'] = array('inThisAppSearch','inThisAppNotSearch','InSearchQuestionMark','thisAppSearchableNotCore','appLoop','hasSearchApp','showTopic','inTopic','notTopic','showForum','inForum','appContextSearch','notCoreApp','lookElsewhere','matchesForums','inThisAppForums','canSearchForums','inThisAppMembers','canSearchMembers','inThisAppCore','canSearchCore');
$this->_funcHooks['shareLinks'] = array('hasOverrideApp','hasCustom','isEnabled','cacheLoop','gotLinks');
$this->_funcHooks['signature_separator'] = array('notMe');
$this->_funcHooks['userHoverCard'] = array('hasClassName','hasTitle','canSeeProfiles','hasMemberId','hasMemberIdClose');
$this->_funcHooks['userInfoPane'] = array('customFields','customFieldsOuter','membertitle','canSeeProfiles','hasVariable','canSeeProfiles2','avatar','rankimageimage','rankimage','postCount','hasWarningId','authorwarn','authorcfields','customFields','customFieldsOuter','membertitle','rankimageimage','rankimage','isfriend','friendop','sendpm','hasblog','hasgallery','ismember','authorcfields','changewarn','highwarn','authorwarn');
$this->_funcHooks['userSmallPhoto'] = array('linkAvatarOpen','hasAlt','hasCustomClass','hasphoto','linkAvatarClose','linkAvatarOpen','hasAlt','hasCustomClass','hasphoto','linkAvatarClose');
$this->_funcHooks['warnDetails'] = array('actionIsPermanent','hasAction','actions','hasReasonAndContent','hasContent','hasReason','hasExpireDate','canExpire','hasPoint','isVerbalOnly','hasModAndMemberNote','hasMemberNote','canSeeModNote','actionIsPermanent','hasAction','actions','hasReasonAndContent','hasContent','hasReason','hasExpireDate','canExpire','hasPoint','isVerbalOnly','hasModAndMemberNote','hasMemberNote','canSeeModNote');


}

/* -- defaultHeader --*/
function defaultHeader() {
$IPBHTML = "";
$IPBHTML .= "<h1>
	<a href='{$this->settings['board_url']}' title='{$this->lang->words['go_home']}' rel=\"home\" accesskey='1'>{$this->settings['board_name']}</a>
</h1>";
return $IPBHTML;
}

/* -- facebookShareButton --*/
function facebookShareButton($url, $title) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- forum_jump --*/
function forum_jump($html) {
$IPBHTML = "";
$IPBHTML .= "<form id='forum_jump' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", "public",'' ), "", "" ) . "' method='post'>
		<fieldset>
			<select name='showforum' class='input_select'>
				<optgroup label=\"{$this->lang->words['forum_jump']}\">
					<option value='0'>{$this->lang->words['forum_home']}</option>
					{$html}
				</optgroup>
			</select>
			" . (($this->member->session_type != 'cookie') ? ("<input type='hidden' name='s' value='{$this->member->session_id}' />") : ("")) . "
			<input type='submit' value='{$this->lang->words['jmp_go']}' class='input_submit alt' />
		</fieldset>
	</form>";
return $IPBHTML;
}

/* -- globalTemplate --*/
function globalTemplate($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['globalTemplate'] ) )
{
$count_a8d1f3a4af317c9ca27f8ac12ff19dcb = is_array($this->functionData['globalTemplate']) ? count($this->functionData['globalTemplate']) : 0;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['html'] = $html;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['documentHeadItems'] = $documentHeadItems;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['css'] = $css;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['jsModules'] = $jsModules;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['metaTags'] = $metaTags;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['header_items'] = $header_items;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['items'] = $items;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['footer_items'] = $footer_items;
$this->functionData['globalTemplate'][$count_a8d1f3a4af317c9ca27f8ac12ff19dcb]['stats'] = $stats;
}
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
	<html xml:lang=\"en\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"" . ((IPSLib::fbc_enabled() === TRUE || $this->settings['fbc_appid']) ? (" xmlns:fb=\"http://www.facebook.com/2008/fbml\"") : ("")) . ">
	<head>
		<meta http-equiv=\"content-type\" content=\"text/html; charset={$this->settings['gb_char_set']}\" />
		<title>{$header_items['title']}" . (($header_items['page']) ? (" {$this->lang->words['page_title_page']} {$header_items['page']}") : ("")) . "</title>
		<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />-->
		<link rel=\"shortcut icon\" href='" . (($this->registry->output->isHTTPS) ? ("{$this->settings['board_url_https']}") : ("{$this->settings['board_url']}")) . "/favicon.ico' />
		<meta property=\"og:title\" content=\"{$this->registry->output->encodeMetaTagContent( str_replace( ' - ' . $this->settings['board_name'], '', $header_items['title'] ) )}\"/>
		<meta property=\"og:site_name\" content=\"{$this->registry->output->encodeMetaTagContent( $this->settings['board_name'] )}\"/>
		<meta property=\"og:image\" content=\"{$this->settings['meta_imagesrc']}\"/>
		<meta property=\"og:type\" content=\"article\" />
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeMeta' ) ? $this->registry->getClass('output')->getTemplate('global')->includeMeta($metaTags) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeVars' ) ? $this->registry->getClass('output')->getTemplate('global')->includeVars() : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeJS' ) ? $this->registry->getClass('output')->getTemplate('global')->includeJS($jsModules) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeCSS' ) ? $this->registry->getClass('output')->getTemplate('global')->includeCSS($css) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeFeeds' ) ? $this->registry->getClass('output')->getTemplate('global')->includeFeeds($documentHeadItems) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeRTL' ) ? $this->registry->getClass('output')->getTemplate('global')->includeRTL() : '' ) . "
		
		<!--<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">-->
		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />
		<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1, user-scalable=no\">
	</head>
	<body id='ipboard_body'>
		<div id='ipbwrapper'>
			" . ((count( $items['navigation'] ) > 1 && !$this->settings['_mobile_nav_home']) ? ("" . (($this->nav_count=count($items['navigation'])) ? ("") : ("")) . "" . (($this->nav_back = ( isset( $this->settings['_mobile_back_nav'] ) ) ? $this->settings['_mobile_back_nav'] : 2) ? ("") : ("")) . "
				<div id='secondary_navigation'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$items['navigation'][ $this->nav_count - $this->nav_back ][1]}", "{$items['navigation'][ $this->nav_count - $this->nav_back ][4]}",'' ), "{$items['navigation'][ $this->nav_count - $this->nav_back ][2]}", "{$items['navigation'][ $this->nav_count - $this->nav_back ][3]}" ) . "'>{$this->lang->words['_larr']} &nbsp;{$items['navigation'][ $this->nav_count - $this->nav_back ][0]}</a>
				</div>") : ("" . ((( count( $items['navigation'] ) == 1 || $this->settings['_mobile_nav_home'] ) && ! $this->settings['_mobile_hide_nav']) ? ("
					<div id='secondary_navigation'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "act=idx", "public",'' ), "false", "" ) . "' class='back'>{$this->lang->words['_larr']} {$this->lang->words['home']}</a>
					</div>
				") : ("")) . "")) . "
			" . ((method_exists( $this->registry->output->getTemplate( $this->registry->getCurrentApplication() . '_global' ), 'overwriteHeader' )) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate(''.$this->registry->getCurrentApplication().'_global'), 'overwriteHeader' ) ? $this->registry->getClass('output')->getTemplate(''.$this->registry->getCurrentApplication().'_global')->overwriteHeader() : '' ) . "
			") : ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'defaultHeader' ) ? $this->registry->getClass('output')->getTemplate('global')->defaultHeader() : '' ) . "
			")) . "
			<div id=\"options-button\">&raquo;</div>
			<div id='user_navigation' class='clearfix'>
				<ul class='clearfix' id='user_bar'>
					" . ((!$this->memberData['member_id']) ? ("
						<a class='button secondary' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", "public",'' ), "", "" ) . "' title='{$this->lang->words['sign_in']}'>{$this->lang->words['sign_in']}</a>&nbsp;&nbsp;&nbsp;
						<a class='button secondary' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=register", "public",'' ), "", "" ) . "\" title='{$this->lang->words['register']}'>{$this->lang->words['register']}</a>
					") : ("
						<a class='button secondary' style='width:auto' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=logout&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "\">{$this->lang->words['log_out']} {$this->memberData['members_display_name']}</a>
					")) . "
				</ul>
				<ul class='clearfix launcher'>
					" . (($this->memberData['member_id'] AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0) ? ("<li id='nav_messages'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging", "public",'' ), "", "" ) . "' title='{$this->lang->words['your_messenger']}'><span class='icon'></span>" . (($this->memberData['msg_count_new']) ? ("<span class='ipsHasNotifications'>{$this->memberData['msg_count_new']}</span>") : ("")) . "{$this->lang->words['your_messenger']}</a></li>") : ("")) . "
					" . (($this->memberData['member_id']) ? ("<li id='nav_notifications'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=core&amp;area=notificationlog&amp;clear=true", "public",'' ), "", "" ) . "'><span class='icon'></span>" . (($this->memberData['notification_cnt']) ? ("<span class='ipsHasNotifications'>{$this->memberData['notification_cnt']}</span>") : ("")) . "{$this->lang->words['notifications_at_the_top']}</a></li>") : ("")) . "
					" . (($header_items['applications']['members']['app_show']) ? ("
						<li id='nav_members'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$header_items['applications']['members']['app_link']}", "{$header_items['applications']['members']['app_base']}",'' ), "{$header_items['applications']['members']['app_seotitle']}", "{$header_items['applications']['members']['app_template']}" ) . "' title='" . sprintf( $this->lang->words['go_to_prefix'], IPSLib::getAppTitle('members') ) . "'><span class='icon'></span>" . IPSLib::getAppTitle('members') . "</a></li>
					") : ("")) . "
					" . (($header_items['applications']['forums']['app_show']) ? ("
						<li id='nav_forums'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$header_items['applications']['forums']['app_link']}", "{$header_items['applications']['forums']['app_base']}",'' ), "{$header_items['applications']['forums']['app_seotitle']}", "{$header_items['applications']['forums']['app_template']}" ) . "' title='" . sprintf( $this->lang->words['go_to_prefix'], IPSLib::getAppTitle('forums') ) . "'><span class='icon'></span>" . IPSLib::getAppTitle('forums') . "</a></li>
					") : ("")) . "
					" . (($header_items['applications']['blog']['app_show']) ? ("
						<li id='nav_blog'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$header_items['applications']['blog']['app_link']}", "{$header_items['applications']['blog']['app_base']}",'' ), "{$header_items['applications']['blog']['app_seotitle']}", "{$header_items['applications']['blog']['app_template']}" ) . "' title='" . sprintf( $this->lang->words['go_to_prefix'], IPSLib::getAppTitle('blog') ) . "'><span class='icon'></span>" . IPSLib::getAppTitle('blog') . "</a></li>
					") : ("")) . "
					" . (($header_items['applications']['gallery']['app_show']) ? ("
						<li id='nav_gallery'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$header_items['applications']['gallery']['app_link']}", "{$header_items['applications']['gallery']['app_base']}",'' ), "{$header_items['applications']['gallery']['app_seotitle']}", "{$header_items['applications']['gallery']['app_template']}" ) . "' title='" . sprintf( $this->lang->words['go_to_prefix'], IPSLib::getAppTitle('gallery') ) . "'><span class='icon'></span>" . IPSLib::getAppTitle('gallery') . "</a></li>
					") : ("")) . "
					" . (($header_items['applications']['nexus']['app_show']) ? ("
						<li id='nav_nexus_store'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=nexus&amp;module=payments&amp;section=store", "public",'' ), "store", "" ) . "'><span class='icon'></span>{$this->lang->words['mobile_nexus_store']}</a></li>
						<li id='nav_nexus_ca'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=nexus&amp;module=clients", "public",'' ), "", "" ) . "'><span class='icon'></span>{$this->lang->words['mobile_nexus_clients']}</a></li>
					") : ("")) . "
					<li id='nav_vnc'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=viewNewContent&amp;search_app=" . (($this->registry->getCurrentApplication() != 'core' AND IPSLib::appIsSearchable( $this->registry->getCurrentApplication() )) ? ("{$this->registry->getCurrentApplication()}") : ("forums")) . "", "public",'' ), "", "" ) . "' accesskey='2'><span class='icon'></span>{$this->lang->words['mobile_view_new_posts']}</a></li>
					<li id='nav_statuses'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "'><span class='icon'></span>{$this->lang->words['mob_status_updates']}</a></li>
					<li id='nav_search'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search", "public",'' ), "", "" ) . "' accesskey='2'><span class='icon'></span>{$this->lang->words['sj_search']}</a></li>
					<li id='nav_markread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=all&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "\" title='{$this->lang->words['mark_all_as_read']}'><span class='icon'></span>{$this->lang->words['mobile_mark_board_as_read']}</a></li>
				</ul>
			</div>
			<script type=\"text/javascript\">
				/* Prevent flash of header */
				document.getElementById('user_navigation').style.display = 'none';
			</script>
			
			<div id='content' class='clear'>
				" . (($html) ? ("{$html}") : ("")) . "
			</div>
			<div id='footer' class='clear'>
				" . ((( $this->memberData['userAgentType'] != 'mobileAppLegacy' || $this->registry->output->isLargeTouchDevice() )) ? ("
					<a id='full_version' href='#'>{$this->lang->words['full_version']}</a>
				") : ("")) . "
				" . ((count( $footer_items['lang_chooser']['options'] ) > 1) ? ("
					<a href='#' id='show_langs'>{$footer_items['lang_chooser']['default']}</a>
					<div id='show_langs_box' style='display: none'>
						<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_formatted']}", "public",'' ), "", "" ) . "\" method=\"post\">
							<fieldset>
								<input type='hidden' name='k' value='{$this->member->form_hash}' />
								<input type='hidden' name='setlanguage' value='1' />
								<input type=\"hidden\" name=\"langurlbits\" value=\"&amp;cal_id={$this->request['cal_id']}\" />
								<label for='newLang' class='hide'>{$this->lang->words['language_prefix']}</label>
								<select name=\"langid\" id='newLang'>
									".$this->__f__5e3cdfcdb13824f97d8082326090817d($html,$documentHeadItems,$css,$jsModules,$metaTags,$header_items,$items,$footer_items,$stats)."								</select>
								<input type='submit' class='input_submit alt' value='{$this->lang->words['jmp_go']}' id='newLangSubmit' />
							</fieldset>
						</form>
					</div>
				") : ("")) . "
			</div>
			<div id='task'>{$stats['task']}</div>
		</div>
		<div id='shade' style='display:none'></div>
		<!-- pre-load -->
		<div style='display:none'><img src='{style_images_url}/wait.gif' /></div>
		
		" . (($this->settings['viglink_enabled'] and ( !$this->settings['viglink_groups'] or IPSMember::isInGroup( $this->memberData, explode( ',', $this->settings['viglink_groups'] ) ) )) ? ("<script type=\"text/javascript\">
			  var vglnk = { api_url: '//api.viglink.com/api',
			                key: '{$this->settings['viglink_api_key']}'" . (($this->settings['viglink_subid']) ? (",
			                sub_id: '{$this->settings['sub_id']}'
			                ") : ("")) . "
			              };
			
			  (function(d, t) {
			    var s = d.createElement(t); s.type = 'text/javascript'; s.async = true;
			    s.src = ('https:' == document.location.protocol ? vglnk.api_url :
			             '//cdn.viglink.com/api') + '/vglnk.js';
			    var r = d.getElementsByTagName(t)[0]; r.parentNode.insertBefore(s, r);
			  }(document, 'script'));
			</script>") : ("")) . "
		
	</body>
</html>";
return $IPBHTML;
}


function __f__5e3cdfcdb13824f97d8082326090817d($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $footer_items['lang_chooser']['options'] as $lang )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
										<option value='{$lang['id']}' " . (($lang['selected']) ? ("selected='selected'") : ("")) . ">
											{$lang['title']}
										</option>
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- googlePlusOneButton --*/
function googlePlusOneButton($url, $title, $params) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- include_highlighter --*/
function include_highlighter($load_when_needed=0) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- include_lightbox --*/
function include_lightbox() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- include_lightbox_real --*/
function include_lightbox_real() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- includeCSS --*/
function includeCSS($css) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeCSS'] ) )
{
$count_5c046bb1b8cac6310529717a7e966cc3 = is_array($this->functionData['includeCSS']) ? count($this->functionData['includeCSS']) : 0;
$this->functionData['includeCSS'][$count_5c046bb1b8cac6310529717a7e966cc3]['css'] = $css;
}

$this->minify = array();
$IPBHTML .= "" . ((is_array( $css['import'] )) ? ("" . (($this->settings['use_minify']) ? ("") : ("")) . "
	".$this->__f__7fda8e62ce919153576dbeecfb97708c($css)."	" . (($this->settings['use_minify'] AND count($this->minify)) ? ("
		<link rel=\"stylesheet\" type=\"text/css\" media='screen,print' href=\"{$this->settings['css_base_url']}min/index.php?ipbv={$this->registry->output->antiCacheHash}&amp;f=" . str_replace( $this->settings['css_base_url'], PUBLIC_DIRECTORY . '/', implode( ',', $this->minify ) ) . "\" />
	") : ("")) . "") : ("")) . "
" . ((is_array( $css['inline'] ) AND count( $css['inline'] )) ? ("
	".$this->__f__82a2abbfb543123815678dcee1583d44($css)."") : ("")) . "";
return $IPBHTML;
}


function __f__7fda8e62ce919153576dbeecfb97708c($css)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['import'] as $data )
	{
		
$importCss = true;
			if( stripos( $data['content'], $this->settings['css_base_url'] ) === 0 && $this->settings['use_minify'] AND ( ! $data['attributes'] OR stripos( $data['attributes'], 'screen' ) !== false ) )
			{
				$importCss		= false;
				$this->minify[]	= "{$data['content']}";
			}

		$__iteratorCount++;
		$_ips___x_retval .= "
				" . (($importCss) ? ("
			<link rel=\"stylesheet\" type=\"text/css\" {$data['attributes']} href=\"{$data['content']}?ipbv={$this->registry->output->antiCacheHash}\" />
		") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__82a2abbfb543123815678dcee1583d44($css)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['inline'] as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<style type=\"text/css\" {$data['attributes']}>
		/* Inline CSS */
		{$data['content']}
	</style>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- includeFeeds --*/
function includeFeeds($documentHeadItems) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeFeeds'] ) )
{
$count_8b638de8a7dc84d28e22bf01689495aa = is_array($this->functionData['includeFeeds']) ? count($this->functionData['includeFeeds']) : 0;
$this->functionData['includeFeeds'][$count_8b638de8a7dc84d28e22bf01689495aa]['documentHeadItems'] = $documentHeadItems;
}
$IPBHTML .= "" . ((count($documentHeadItems)) ? ("
	".$this->__f__d3495139f54821b77d67d77aec97ddc9($documentHeadItems)."") : ("")) . "";
return $IPBHTML;
}


function __f__f5c13b41d84162f8488de260bbcc1a74($documentHeadItems,$type='',$idx='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems[ $type ] as $idx => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($type == 'javascript') ? ("
				<script type=\"text/javascript\" src=\"{$data}\" charset=\"<% CHARSET %>\"></script>
			") : ("")) . "
			" . (($type == 'rss') ? ("
				<link rel=\"alternate\" type=\"application/rss+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
			") : ("")) . "
			" . (($type == 'rsd') ? ("
				<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
			") : ("")) . "
			" . (($type == 'raw') ? ("
				{$data}
			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d3495139f54821b77d67d77aec97ddc9($documentHeadItems)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems as $type => $idx )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		".$this->__f__f5c13b41d84162f8488de260bbcc1a74($documentHeadItems,$type,$idx)."	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- includeJS --*/
function includeJS($jsModules) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeJS'] ) )
{
$count_9c3b9bb82fd973a6f88e7b44e28bfc6d = is_array($this->functionData['includeJS']) ? count($this->functionData['includeJS']) : 0;
$this->functionData['includeJS'][$count_9c3b9bb82fd973a6f88e7b44e28bfc6d]['jsModules'] = $jsModules;
}
$IPBHTML .= "" . (($this->settings['use_minify']) ? ("
	<script type='text/javascript' src='{$this->settings['public_dir']}min/index.php?g=js'></script>
") : ("
	<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/prototype.js'></script>
")) . "
<script type=\"text/javascript\" >
var LOADING_TEMPLATE = new Template( \"<div id='loadingBox'><img src='{style_images_url}/wait.gif' /><span>{$this->lang->words['loadingtext']}</span></div>\" );
</script>
<script type=\"text/javascript\" src='{$this->settings['cache_dir']}lang_cache/{$this->lang->lang_id}/ipb.lang.js' charset='{$this->settings['gb_char_set']}'></script>
<!--Remove if you don't want touch devices-->
<script type=\"text/javascript\" src=\"{$this->settings['public_dir']}js/mobile_touch.js\"></script>
<!-- Fix youtube video sizes -->
<script type='text/javascript'>
	Event.observe( window, 'resize', handleEmbeddedVideo );
	Event.observe( window, 'load', handleEmbeddedVideo );

	function handleEmbeddedVideo(e)
	{
		var pageWidth	= $('content').getWidth() - 40;

		$$('.EmbeddedVideo', '.EmbeddedVideo embed').each( function(elem){
			var aspectRatio = $(elem).readAttribute('height') / $(elem).readAttribute('width');

			if( $(elem).readAttribute('width') > pageWidth )
			{
				$(elem).writeAttribute( { width: pageWidth, height: pageWidth * aspectRatio });
			}
		});
	}
</script>
<script type='text/javascript'>
	document.observe(\"dom:loaded\", function(){
					  		
		$$('.bbc_spoiler_show').find( function( elem ) {
			elem.addClassName( 'button page-button' ).setStyle( { 'font-size' : '12px', 'padding': '5px' } );
			elem.observe('click', _fireSpoiler );
		} ) 
	
	} );
		
	function _fireSpoiler(e)
	{
		button = Event.element(e);
		
		Event.stop(e);
	
		var returnvalue = $(button).up().down('.bbc_spoiler_wrapper').down('.bbc_spoiler_content').toggle();
		
		if( returnvalue.visible() )
		{
			$(button).value = \"{$this->lang->words['spoiler_hide']}\";
		}
		else
		{
			$(button).value = \"{$this->lang->words['spoiler_show']}\";
		}
	}		
</script>";
return $IPBHTML;
}

/* -- includeMeta --*/
function includeMeta($metaTags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeMeta'] ) )
{
$count_bb5a9ecb3c1fb4cf1a18e7d0d0b04b41 = is_array($this->functionData['includeMeta']) ? count($this->functionData['includeMeta']) : 0;
$this->functionData['includeMeta'][$count_bb5a9ecb3c1fb4cf1a18e7d0d0b04b41]['metaTags'] = $metaTags;
}
$IPBHTML .= "" . ((is_array( $metaTags ) AND count( $metaTags )) ? ("
	".$this->__f__b99efb50152d868f4a1c1e9f1eef9391($metaTags)."") : ("")) . "
<meta property=\"og:image\" content=\"{$this->settings['meta_imagesrc']}\"/>";
return $IPBHTML;
}


function __f__757f8ce7b2c49cb28c4596c596f0bdec($metaTags,$tag='',$id='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $metaTags[ $tag ] as $content )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		" . ((stristr( $tag, 'og:' )) ? ("
			<meta property=\"{$tag}\" content=\"{$content}\" />
		") : ("
			<meta name=\"{$tag}\" content=\"{$content}\" />
		")) . "
		" . (($tag == 'identifier-url') ? ("
			<meta property=\"og:url\" content=\"{$content}\" />
		") : ("")) . "
		" . (($tag == 'description') ? ("
			<meta property=\"og:description\" content=\"{$content}\" />
		") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__b99efb50152d868f4a1c1e9f1eef9391($metaTags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $metaTags as $tag => $id )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		".$this->__f__757f8ce7b2c49cb28c4596c596f0bdec($metaTags,$tag,$id)."	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- includeRTL --*/
function includeRTL() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeRTL'] ) )
{
$count_8de2bc931b3431045909f1b667767be6 = is_array($this->functionData['includeRTL']) ? count($this->functionData['includeRTL']) : 0;
}

$this->isRtlLang	= false;
$IPBHTML .= "".$this->__f__bb73cdecd67bee20f860674cb1fe5c89()."<script type='text/javascript'>
	var isRTL	= false;
	var rtlIe	= '';
	var rtlFull	= '';
</script>
" . (($this->isRtlLang AND is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl.css' )) ? ("
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\" />
	<script type='text/javascript'>
		var rtlFull	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\";
		var isRTL	= true;
	</script>
") : ("" . (($this->isRtlLang AND is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl.css' )) ? ("
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl.css\" />
		<script type='text/javascript'>
			var rtlFull	= \"{$this->settings['public_dir']}style_css/ipb_rtl.css\";
			var isRTL	= true;
		</script>
	") : ("")) . "")) . "
" . (($this->isRtlLang AND is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl_ie.css' )) ? ("
	<!--[if lte IE 7]>
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\" />
	<![endif]-->
	<script type='text/javascript'>
		var rtlIe	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\";
	</script>
") : ("" . (($this->isRtlLang AND is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl_ie.css' )) ? ("
		<!--[if lte IE 7]>
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\" />
		<![endif]-->
		<script type='text/javascript'>
			var rtlIe	= \"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\";
		</script>
	") : ("")) . "")) . "";
return $IPBHTML;
}


function __f__bb73cdecd67bee20f860674cb1fe5c89()
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $this->cache->getCache('lang_data') as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . ((intval($this->member->language_id) == intval($data['lang_id'])) ? ("" . (($data['lang_isrtl']) ? ("" . (($this->isRtlLang = true) ? ("") : ("")) . "") : ("")) . "") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- includeVars --*/
function includeVars($header_items=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['includeVars'] ) )
{
$count_ce4aa12cd4e3ed7327d3a1729275cbe4 = is_array($this->functionData['includeVars']) ? count($this->functionData['includeVars']) : 0;
$this->functionData['includeVars'][$count_ce4aa12cd4e3ed7327d3a1729275cbe4]['header_items'] = $header_items;
}
$IPBHTML .= "<script type='text/javascript'>

var ipb = { 
	vars: {
		base_url: 	'" . (($this->registry->output->isHTTPS) ? ("" . str_replace( 'http://', 'https://', "{$this->settings['js_base']}" ) . "") : ("{$this->settings['js_base']}")) . "',
		board_url: 	'{$this->settings['board_url']}',
		img_url: 	'{$this->settings['img_url']}',
		active_app: 	'{$this->registry->getCurrentApplication()}',
		upload_url: 	'{$this->settings['upload_url']}',
		member_id: 		parseInt( {$this->memberData['member_id']} ),
		is_supmod: 		parseInt( " . intval($this->memberData['g_is_supmod']) . " ),
		is_admin: 		parseInt( {$this->memberData['g_access_cp']} ),
		secure_hash: 	'{$this->member->form_hash}',
		session_id: 	'{$this->member->session_id}',
		time_offset: \"{$this->settings['time_offset']}\",
		hour_format: \"" . ((strpos( $this->settings['clock_long'], '%p' ) OR strpos( $this->settings['clock_long'], '%P' )) ? ("12") : ("24")) . "\"
	},
	
	lang: {}
};
</script>";
return $IPBHTML;
}

/* -- inlineLogin --*/
function inlineLogin() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['inlineLogin'] ) )
{
$count_0d2bf69b87aa1a443d579415e9541a41 = is_array($this->functionData['inlineLogin']) ? count($this->functionData['inlineLogin']) : 0;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- liveEditJs --*/
function liveEditJs() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['liveEditJs'] ) )
{
$count_9af53165dc36a12645a98fd9efb49445 = is_array($this->functionData['liveEditJs']) ? count($this->functionData['liveEditJs']) : 0;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- metaEditor --*/
function metaEditor($tags, $url) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- nextPreviousTemplate --*/
function nextPreviousTemplate($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['nextPreviousTemplate'] ) )
{
$count_79fd1a8a92ace674620a4b62c270b944 = is_array($this->functionData['nextPreviousTemplate']) ? count($this->functionData['nextPreviousTemplate']) : 0;
$this->functionData['nextPreviousTemplate'][$count_79fd1a8a92ace674620a4b62c270b944]['data'] = $data;
}
$IPBHTML .= "" . (($data['totalItems'] > $data['itemsPerPage']) ? ("" . (($data['_hasPrevious']) ? ("" . (($data['ajaxLoad']) ? ("
			<a class='button page-button prev' href=\"#\" onclick=\"return ipb.global.ajaxPagination( '{$data['ajaxLoad']}', '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;secure_key={$this->member->form_hash}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] - $data['itemsPerPage'] ) . "{$data['anchor']}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "' );\" title=\"{$this->lang->words['tpl_prev']}\" rel='prev'>{$this->lang->words['_larr']} {$this->lang->words['prev']}</a>
		") : ("
			<a class='button page-button prev' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] - $data['itemsPerPage'] ) . "{$data['anchor']}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_prev']}\" rel='prev'>{$this->lang->words['_larr']} {$this->lang->words['prev']}</a>
		")) . "") : ("")) . "
	" . (($data['_hasNext']) ? ("" . (($data['ajaxLoad']) ? ("
			<a class='button page-button next' href=\"#\" onclick=\"return ipb.global.ajaxPagination( '{$data['ajaxLoad']}', '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;secure_key={$this->member->form_hash}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] + $data['itemsPerPage'] ) . "{$data['anchor']}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "' );\" title=\"{$this->lang->words['tpl_next']}\" rel='next'>{$this->lang->words['next']} {$this->lang->words['_rarr']}</a>
		") : ("
			<a class='button page-button next' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] + $data['itemsPerPage'] ) . "{$data['anchor']}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_next']}\" rel='next'>{$this->lang->words['next']} {$this->lang->words['_rarr']}</a>
		")) . "") : ("")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- paginationTemplate --*/
function paginationTemplate($work, $data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['paginationTemplate'] ) )
{
$count_d490046b20f6cffa3b67c3f141fee76a = is_array($this->functionData['paginationTemplate']) ? count($this->functionData['paginationTemplate']) : 0;
$this->functionData['paginationTemplate'][$count_d490046b20f6cffa3b67c3f141fee76a]['work'] = $work;
$this->functionData['paginationTemplate'][$count_d490046b20f6cffa3b67c3f141fee76a]['data'] = $data;
}
$IPBHTML .= "" . (($work['pages'] > 1) ? ("" . (($work['current_page'] > 1) ? ("
		<a class=\"button page-button prev\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$this->registry->output->generatePaginationUrlBit( intval( $data['currentStartValue'] - $data['itemsPerPage'] ), $data )}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_prev']}\" rel='prev'>{$this->lang->words['_laquo']} {$this->lang->words['mob_prev']}</a>
	") : ("
		<a class=\"button page-button disabled prev\" href=\"#\">{$this->lang->words['_laquo']} {$this->lang->words['mob_prev']}</a>
	")) . "
	" . (($work['current_page'] < $work['pages']) ? ("
		<a class=\"button page-button next\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$this->registry->output->generatePaginationUrlBit( intval( $data['currentStartValue'] + $data['itemsPerPage'] ), $data )}", "{$data['base']}",'' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_next']}\" rel='next'>{$this->lang->words['mob_next']} {$this->lang->words['_raquo']}</a>
	") : ("
		<a class=\"button page-button disabled next\" href=\"#\">{$this->lang->words['mob_next']} {$this->lang->words['_raquo']}</a>
	")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- quickSearch --*/
function quickSearch() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['quickSearch'] ) )
{
$count_ff90aee7af35b61240196626556533a4 = is_array($this->functionData['quickSearch']) ? count($this->functionData['quickSearch']) : 0;
}
$IPBHTML .= "<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=search", "public",'' ), "", "" ) . "\" method=\"post\" id='search-box' >
<input type='search' name='search_term' id='main_search' size='24' />
<input type='submit' class='button' value='{$this->lang->words['sj_search']}' />
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search", "public",'' ), "", "" ) . "' title='{$this->lang->words['advanced_search']}' accesskey='4' rel=\"search\" id='adv_search' class='button'>{$this->lang->words['more']}</a>
</form>";
return $IPBHTML;
}

/* -- shareLinks --*/
function shareLinks($links, $title='', $url='', $cssClass='topic_share left') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['shareLinks'] ) )
{
$count_835a608304cb1cb0ca9a4d2c4a32ddde = is_array($this->functionData['shareLinks']) ? count($this->functionData['shareLinks']) : 0;
$this->functionData['shareLinks'][$count_835a608304cb1cb0ca9a4d2c4a32ddde]['links'] = $links;
$this->functionData['shareLinks'][$count_835a608304cb1cb0ca9a4d2c4a32ddde]['title'] = $title;
$this->functionData['shareLinks'][$count_835a608304cb1cb0ca9a4d2c4a32ddde]['url'] = $url;
$this->functionData['shareLinks'][$count_835a608304cb1cb0ca9a4d2c4a32ddde]['cssClass'] = $cssClass;
}
$IPBHTML .= "&nbsp;";
return $IPBHTML;
}

/* -- signature_separator --*/
function signature_separator($sig="", $author_id=0, $can_ignore=true) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['signature_separator'] ) )
{
$count_712519dbab58222234e305cfe79f7608 = is_array($this->functionData['signature_separator']) ? count($this->functionData['signature_separator']) : 0;
$this->functionData['signature_separator'][$count_712519dbab58222234e305cfe79f7608]['sig'] = $sig;
$this->functionData['signature_separator'][$count_712519dbab58222234e305cfe79f7608]['author_id'] = $author_id;
$this->functionData['signature_separator'][$count_712519dbab58222234e305cfe79f7608]['can_ignore'] = $can_ignore;
}
$IPBHTML .= "<div class=\"signature\">
	{$sig}
</div>";
return $IPBHTML;
}

/* -- userHoverCard --*/
function userHoverCard($member=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['userHoverCard'] ) )
{
$count_74500f8f208e085f118b0653ff994de3 = is_array($this->functionData['userHoverCard']) ? count($this->functionData['userHoverCard']) : 0;
$this->functionData['userHoverCard'][$count_74500f8f208e085f118b0653ff994de3]['member'] = $member;
}
$IPBHTML .= "" . (($member['member_id']) ? ("<a data-ipb=\"noparse\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "\" title=\"{$this->lang->words['view_profile']}\">") : ("")) . "{$member['members_display_name']}" . (($member['member_id']) ? ("</a>") : ("")) . "";
return $IPBHTML;
}

/* -- userInfoPane --*/
function userInfoPane($author, $contentid, $options) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['userInfoPane'] ) )
{
$count_ea6e39f790f57ac11008f2c1940f0cd7 = is_array($this->functionData['userInfoPane']) ? count($this->functionData['userInfoPane']) : 0;
$this->functionData['userInfoPane'][$count_ea6e39f790f57ac11008f2c1940f0cd7]['author'] = $author;
$this->functionData['userInfoPane'][$count_ea6e39f790f57ac11008f2c1940f0cd7]['contentid'] = $contentid;
$this->functionData['userInfoPane'][$count_ea6e39f790f57ac11008f2c1940f0cd7]['options'] = $options;
}
$IPBHTML .= "<ul class='user_details'>
		" . (($author['title']) ? ("
			<li class='title'>{$author['title']}</li>
		") : ("")) . "
		" . (($author['member_rank_img']) ? ("<li class='group_icon'>
			" . (($author['member_rank_img_i'] == 'img') ? ("
				<img src='{$author['member_rank_img']}' alt='' />
			") : ("
				{$author['member_rank_img']}
			")) . "
			</li>") : ("")) . "
	</ul>
	<div style='margin: 0 auto;'>
		<ul class='user_controls clear'>
			" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $author['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends'] && $author['member_id']) ? ("" . ((IPSMember::checkFriendStatus( $author['member_id'] )) ? ("
					<li class='mini_friend_toggle is_friend' id='friend_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$author['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
				") : ("
					<li class='mini_friend_toggle is_not_friend' id='friend_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$author['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>
				")) . "") : ("")) . "
			" . (($this->memberData['g_use_pm'] AND $this->memberData['member_id'] != $author['member_id'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) && $author['member_id']) ? ("
				<li class='pm_button' id='pm_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$author['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['pm_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
			") : ("")) . "
			" . (($author['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;show_members_blogs={$author['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
			") : ("")) . "
			" . (($author['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$author['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
			") : ("")) . "
		</ul>
	</div>
	<ul class='user_fields'>
		<li>
			<span class='ft'>{$this->lang->words['m_group']}</span>
			<span class='fc'>{$author['_group_formatted']}</span>
		</li>
		" . (($author['member_id']) ? ("
			<li>
				<span class='ft'>{$this->lang->words['m_posts']}</span>
				<span class='fc'>" . $this->registry->getClass('class_localization')->formatNumber( intval( $author['posts'] ) ) . "</span>
			</li>
			<li>
				<span class='ft'>{$this->lang->words['m_joined']}</span>
				<span class='fc'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($author['joined'],"joined", 0)) . "</span>
			</li>
		") : ("")) . "
		" . (($author['custom_fields'] != "") ? ("
			".$this->__f__a15eb1248d9899f35f6d81883fae803a($author,$contentid,$options)."		") : ("")) . "
	</ul>
	" . (($author['warn_percent'] !== NULL) ? ("<br class='clear' />
		<div class='warn_panel clear rounded'>
			" . (($author['can_edit_warn']) ? ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=modcp&amp;section=editmember&amp;type=add&amp;mid={$author['member_id']}&amp;t={$this->request['t']}&amp;st={$this->request['st']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['warn_increase']}'><img src='{$this->settings['img_url']}/warn_add.gif' alt='{$this->lang->words['add']}' class='warn_edit up' /></a><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=modcp&amp;section=editmember&amp;type=minus&amp;mid={$author['member_id']}&amp;t=0&amp;st=0", "public",'' ), "", "" ) . "' title='{$this->lang->words['warn_decrease']}'><img src='{$this->settings['img_url']}/warn_minus.gif' alt='{$this->lang->words['minus']}' class='warn_edit down'  /></a>
			") : ("")) . "
				<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=modcp&amp;section=editmember&amp;do=view&amp;mid={$author['member_id']}", "public",'' ), "", "" ) . "' id='warn_link_{$contentid}_{$author['member_id']}' title='{$this->lang->words['warn_view_history']}' class='warn_link'>{$this->lang->words['warn_status']}</a></strong>
			" . (($author['warn_percent'] >= 80) ? ("
				<p class='progress_bar user_warn limit' title='{$this->lang->words['warn_level']} {$author['warn_percent']}%'>
			") : ("
				<p class='progress_bar user_warn' title='{$this->lang->words['warn_level']} {$author['warn_percent']}%'>
			")) . "
				<span style='width: {$author['warn_percent']}%'><span>{$this->lang->words['warn_level']} {$author['warn_percent']}%</span></span>
			</p>
		</div>") : ("")) . "";
return $IPBHTML;
}


function __f__bc84a1078cd9b81202107b7e06aa9591($author, $contentid, $options,$group='',$data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $author['custom_fields'][ $group ] as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($field != '') ? ("
						<li>
							{$field}
						</li>
					") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__a15eb1248d9899f35f6d81883fae803a($author, $contentid, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $author['custom_fields'] as $group => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				".$this->__f__bc84a1078cd9b81202107b7e06aa9591($author,$contentid,$options,$group,$data)."			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- userSmallPhoto --*/
function userSmallPhoto($member=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['userSmallPhoto'] ) )
{
$count_c10b9c9e39a077a96d01b18db54df608 = is_array($this->functionData['userSmallPhoto']) ? count($this->functionData['userSmallPhoto']) : 0;
$this->functionData['userSmallPhoto'][$count_c10b9c9e39a077a96d01b18db54df608]['member'] = $member;
}
$IPBHTML .= "" . (($member['member_id'] && ( $this->memberData['g_is_supmod'] || ($this->memberData['g_mem_info'] && ! IPSMember::isInactive($member) ) )) ? ("
	<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink left'>
") : ("
	<div class='left'>
")) . "
" . (($member['member_id']) ? ("<img src='{$member['pp_small_photo']}' alt='" . (($member['alt']) ? ("{$member['alt']}") : ("{$this->lang->words['photo']}")) . "' class='ipsUserPhoto " . ((empty($member['_customClass'])) ? ("ipsUserPhoto_mini") : ("{$member['_customClass']}")) . "' />") : ("
	" . IPSMember::buildNoPhoto(0, 'mini' ) . "
")) . "
" . (($member['member_id'] && ( $this->memberData['g_is_supmod'] || ($this->memberData['g_mem_info'] && ! IPSMember::isInactive($member) ) )) ? ("
	</a>
") : ("
	</div>
")) . "";
return $IPBHTML;
}

/* -- warnDetails --*/
function warnDetails($warning, $canSeeModNote) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global', $this->_funcHooks['warnDetails'] ) )
{
$count_3ba97f792f59e8645875ec1c65618472 = is_array($this->functionData['warnDetails']) ? count($this->functionData['warnDetails']) : 0;
$this->functionData['warnDetails'][$count_3ba97f792f59e8645875ec1c65618472]['warning'] = $warning;
$this->functionData['warnDetails'][$count_3ba97f792f59e8645875ec1c65618472]['canSeeModNote'] = $canSeeModNote;
}
$IPBHTML .= "<h3>{$this->lang->words['warnings_details']}</h3>
<div class='ipsBox'>
	<p class='message unspecific'>
		" . (($warning['wl_reason']) ? ("" . (($warning['content']) ? ("
				" . sprintf( $this->lang->words['warning_blurb_yy'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['wl_reason'], $warning['content'] ) . "
			") : ("
				" . sprintf( $this->lang->words['warning_blurb_yn'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['wl_reason'] ) . "
			")) . "") : ("" . (($warning['content']) ? ("
				" . sprintf( $this->lang->words['warning_blurb_ny'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['content'] ) . "
			") : ("
				" . sprintf( $this->lang->words['warning_blurb_nn'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "" ) . "
			")) . "")) . "
		<br />
		" . ((!$warning['wl_points'] and !$warning['wl_mq'] and !$warning['wl_rpa'] and !$warning['wl_suspend']) ? ("
			{$this->lang->words['warnings_verbal_only']}
		") : ("" . (($warning['wl_points']) ? ("" . (($warning['wl_expire']) ? ("" . (($warning['wl_expire_date']) ? ("
						" . sprintf( $this->lang->words['warnings_given_points_expire'], $warning['wl_points'], $this->lang->getDate( $warning['wl_expire_date'], 'SHORT' ) ) . "<br />
					") : ("
						" . sprintf( $this->lang->words['warnings_given_points_expired'], $warning['wl_points'] ) . "<br />
					")) . "") : ("
					" . sprintf( $this->lang->words['warnings_given_points'], $warning['wl_points'] ) . "<br />
				")) . "") : ("")) . "
			".$this->__f__e999ae2e3549fd4beb255f4ec6085061($warning,$canSeeModNote)."")) . "
	</p>
	" . (($canSeeModNote and $warning['wl_note_mods']) ? ("<div class='ipsBox_container ipsPad'>
			<strong>{$this->lang->words['warnings_note_member']}</strong>
			<br /><br />
			" . (($warning['wl_note_member']) ? ("
				{$warning['wl_note_member']}
			") : ("
				<em>{$this->lang->words['warnings_no_note']}</em>
			")) . "
		</div>
		<div class='ipsBox_container ipsPad'>
			<strong>{$this->lang->words['warnings_note_mods']}</strong>
			<br /><br />
			{$warning['wl_note_mods']}
		</div>") : ("<div class='ipsBox_container ipsPad'>
			" . (($warning['wl_note_member']) ? ("
				{$warning['wl_note_member']}
			") : ("
				<em>{$this->lang->words['warnings_no_note']}</em>
			")) . "
		</div>")) . "
</div>";
return $IPBHTML;
}


function __f__e999ae2e3549fd4beb255f4ec6085061($warning, $canSeeModNote)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'mq', 'rpa', 'suspend' ) as $k )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . (($warning[ 'wl_' . $k ]) ? ("" . (($warning[ 'wl_' . $k ] == -1 || $warning[ 'wl_' . $k ] == -2) ? ("
						" . sprintf( $this->lang->words[ 'warnings_' . $k ], $this->lang->words['warnings_permanently'] ) . "<br />
					") : ("
						" . sprintf( $this->lang->words[ 'warnings_' . $k ], sprintf( $this->lang->words['warnings_for'], $warning[ 'wl_' . $k ], $this->lang->words[ 'warnings_time_' . $warning[ 'wl_' . $k . '_unit' ] ] ) ) . "<br />
					")) . "") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>