<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Tue, 11 Jun 2013 11:11:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_forum_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['forumAttachments'] = array('attachments','attachments');
$this->_funcHooks['forumIndexTemplate'] = array('announcedates','announcements','showSubForumsLit','isNotLast','subforums','canSeeLastInfoRedirect','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','lastPosterID','hideDateUrl','hideLastInfo','canSeeLastInfoSubs','forumRedirect','forums','subforumdata','subforums','topics','moderatorpopup','moderatorscomma','moderators','mm','hasFollowData','watchismember','rulesinline','ruleslink','rules','hasannouncements','hassubforums','isGuestPostTopicTop','usercanpost','moderationDropdownLink','markRead','moderationDropdownMenu','topicsismod','ka_last_post','ka_start_date','ka_replies','ka_viewed','ka_viewed','answerLink','answerMenu','topicsismod','canSeeLastInfoHeader','topicsismod','notopicsspan','hastopics','hastopics','isGuestPostTopic','bottomusercanpost','hasmoderators','hasactiveusers','showactiveusers','showtopics','moderationform','hasMultiModeratorOptions','unreadicon','forumRedirect','forums','subforumdata','subforums','announcements','topichasattach','multipages','replylang','queuedtopic','topics','hassubforums','usercanpost','hasannouncements','hastopics','usercanpost','showtopics');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['topic'] = array('nav','haslastpage','pages','queuedisreadif','queuedisreadelse','queuedtopic','hasmodlinks','solvedBadge','archivedBadge','archivingBadge','queuedpostsImg','topicUnapproved','hasPrefix','showForumNav','showReason','topicDeletedReason','hasTags','multipages','canReadPreview','isHot','isMember','replylang','isMemberCloseA','isLink','hasPollBump','canSeeLastInfo','mmtidon','tidRestore','isUnapproved','issupermod','ispinned','islink','closedtopic','opentopic','islink2','topicmoderator','topicIsDeleted','archivedCb','mmicon','adCodeColSpan','adCodeCheck');
$this->_funcHooks['topic_rating_image'] = array('ratinggood','ratings','ratinggood','ratings');
$this->_funcHooks['topicPrefixWrap'] = array('prefix','prefix');


}

/* -- ajax__deleteTopic --*/
function ajax__deleteTopic() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- forumAttachments --*/
function forumAttachments($title, $rows, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['forumAttachments'] ) )
{
$count_3b522a17810d141e0f23e451f7d95130 = is_array($this->functionData['forumAttachments']) ? count($this->functionData['forumAttachments']) : 0;
$this->functionData['forumAttachments'][$count_3b522a17810d141e0f23e451f7d95130]['title'] = $title;
$this->functionData['forumAttachments'][$count_3b522a17810d141e0f23e451f7d95130]['rows'] = $rows;
$this->functionData['forumAttachments'][$count_3b522a17810d141e0f23e451f7d95130]['pages'] = $pages;
}

if ( ! isset( $this->registry->templateStriping['attachies'] ) ) {
$this->registry->templateStriping['attachies'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . (($this->request['module']=='ajax') ? ("<h3>{$this->lang->words['attach_page_title']}: $title</h3>
	" . (($pages) ? ("
		<div class='topic_controls' style='padding-top: 4px;'>{$pages}</div>
	") : ("")) . "") : ("" . (($pages) ? ("
		<div class='topic_controls'>{$pages}</div>
	") : ("")) . "
	<h3 class='maintitle'>{$this->lang->words['attach_page_title']}: $title</h3>")) . "
<table class='ipb_table'>
	<tr class='header'>
		<th>&nbsp;</th>
		<th>{$this->lang->words['attach_title']}</th>
		<th>{$this->lang->words['attach_size']}</th>
		<th>{$this->lang->words['attach_post']}</th>
	</tr>
		" . ((count($rows)) ? ("".$this->__f__4b5145b923b3641e8148ad5fd7293293($title,$rows,$pages)."	") : ("")) . "
</table>
" . (($pages) ? ("
	<br />
	<div class='topic_controls'>{$pages}</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__4b5145b923b3641e8148ad5fd7293293($title, $rows, $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["attachies"] ) . "' id=\"{$data['attach_id']}\">
				<td class=\"altrow short\">
					<img src=\"{$this->settings['mime_img']}/{$data['image']}\" alt=\"{$this->lang->words['attached_file']}\" />
				</td>
				<td>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=attach&amp;section=attach&amp;attach_rel_module=post&amp;attach_id={$data['attach_id']}", "public",'' ), "", "" ) . "\" title=\"{$data['attach_file']}\">{$data['short_name']}</a><br />
					<span class=\"desc\">( {$this->lang->words['attach_hits']}: {$data['attach_hits']} )<br />( {$this->lang->words['attach_post_date']} {$data['attach_date']} )</span>
				</td>
				<td class=\"altrow short\">{$data['real_size']}</td>
				<td class='short'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=findpost&amp;pid={$data['pid']}", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['view_post']}\">{$data['pid']}</a></td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- forumIndexTemplate --*/
function forumIndexTemplate($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['forumIndexTemplate'] ) )
{
$count_a742de13fb2b4e4c80ff9033113eb2f1 = is_array($this->functionData['forumIndexTemplate']) ? count($this->functionData['forumIndexTemplate']) : 0;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['forum_data'] = $forum_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['announce_data'] = $announce_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['topic_data'] = $topic_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['other_data'] = $other_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['multi_mod_data'] = $multi_mod_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['sub_forum_data'] = $sub_forum_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['footer_filter'] = $footer_filter;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['active_user_data'] = $active_user_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['mod_data'] = $mod_data;
$this->functionData['forumIndexTemplate'][$count_a742de13fb2b4e4c80ff9033113eb2f1]['inforum'] = $inforum;
}
$IPBHTML .= "<h2>" . IPSText::truncate( $forum_data['name'] ) . "</h2>
" . ((is_array( $sub_forum_data ) AND count( $sub_forum_data )) ? ("
	<div class='master_list' id='board_index'>
		".$this->__f__09203f95069ea6c4ad8097cdeefde7be($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."	</div>
") : ("")) . "
<div class='master_list'>
	" . (($forum_data['sub_can_post']) ? ("<!--<h2>{$forum_data['name']}</h2>-->
		<div class='controls'>
			<div class='buttons'>
				" . (($forum_data['_user_can_post']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=post&amp;section=post&amp;do=new_post&amp;f={$forum_data['id']}", "publicWithApp",'' ), "", "" ) . "' title='{$this->lang->words['topic_start']}' accesskey='s' class='button'>{$this->lang->words['topic_start']}</a>
				") : ("")) . "
				{$forum_data['SHOW_PAGES']}
			</div>
		</div>
		
		" . ((is_array( $announce_data ) AND count( $announce_data )) ? ("
			".$this->__f__d46d54ff6ea8b5b833a2d7fe6776ea0c($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."		") : ("")) . "
		
		" . ((is_array( $topic_data ) AND count( $topic_data )) ? ("
			<h3>{$this->lang->words['forum_topic_list']}</h3>
			".$this->__f__351d7c63d5ed72ee56bce6ae96a89e4d($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."		") : ("
			<div class='row no_messages'>
				{$this->lang->words['no_topics']}
			</div>
		")) . "
		<div class='controls'>
			<div class='buttons'>
				" . (($forum_data['_user_can_post']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=post&amp;section=post&amp;do=new_post&amp;f={$forum_data['id']}", "publicWithApp",'' ), "", "" ) . "' title='{$this->lang->words['topic_start']}' accesskey='s' class='button'>{$this->lang->words['topic_start']}</a>
				") : ("")) . "
				{$forum_data['SHOW_PAGES']}
			</div>
		</div>") : ("")) . "	
</div>";
return $IPBHTML;
}


function __f__a37aef040e358a92760bd3a00b498085($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1,$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "				
					" . (($forum_data['redirect_on']) ? ("
						<div id=\"forum-{$forum_data['id']}\" class='row touch-row'>
							<div class='icon'>" . $this->registry->getClass('output')->getReplacement("f_redirect") . "</div>
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}' class='title'>{$forum_data['name']}</a>
							<br /><span class='desc'>{$this->lang->words['rd_hits']}: " . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . "</span>
						</div>
					") : ("<div id=\"forum-{$forum_data['id']}\" class='row touch-row'>
							<div class='icon'>
								" . (($forum_data['img_new_post'] != 'f_locked' && strstr( $forum_data['img_new_post'], 'unread' )) ? ("
									<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['bi_markread']}\" class='forum_marker'>
										" . $this->registry->getClass('output')->getReplacement("f_unread") . "
									</a>
								") : ("
									" . $this->registry->getClass('output')->getReplacement("f_read") . "
								")) . "
							</div>
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}' class='title'>{$forum_data['name']}</a>
							<br /><span class='desc'>{$forum_data['topics']} {$this->lang->words['topics']}</span>
						</div>")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__09203f95069ea6c4ad8097cdeefde7be($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sub_forum_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				".$this->__f__a37aef040e358a92760bd3a00b498085($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d46d54ff6ea8b5b833a2d7fe6776ea0c($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $announce_data as $aid => $adata )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<div class='row touch-row' id=\"ann-{$adata['announce_id']}\">
					<div class='icon'>" . $this->registry->getClass('output')->getReplacement("t_announcement") . "</div>
					<div class='rowContent'>
						<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showannouncement={$adata['announce_id']}&amp;f={$forum_data['id']}", "public",'' ), "%%{$adata['announce_title']}%%", "showannouncement" ) . "\" title='{$this->lang->words['view_announcement']}' class='title'>{$adata['announce_title']}</a></strong>
					</div>
				</div>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__351d7c63d5ed72ee56bce6ae96a89e4d($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topic_data as $tid => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . (($data['approved']) ? ("<div class='row touch-row " . (($data['_unreadUrl']) ? ("unread") : ("")) . " " . (($data['_isDeleted']) ? ("moderated") : ("")) . "' id=\"topic-{$data['tid']}\">
						<div class='icon'>
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'generateTopicIcon' ) ? $this->registry->getClass('output')->getTemplate('global_other')->generateTopicIcon($data['folder_img'], $data['_unreadUrl']) : '' ) . "
						</div>
						<div class='rowContent'>
							" . (($data['topic_hasattach']) ? ("
								" . $this->registry->getClass('output')->getReplacement("t_attach") . "
							") : ("")) . "
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;view=getnewpost", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "\" class='topic_title title'>{$data['title']}</a>
							{$data['prefix']}
							" . ((isset( $data['pages'] ) AND is_array( $data['pages'] ) AND count( $data['pages'] )) ? ("
								<span class='mini_pagination'>
									" . sprintf( $this->lang->words['mini_page_count'], $data['pages'][0]['total'] ) . "
								</span>
							") : ("")) . "
							
							<br />
							<span class='subtext'>
								" . $this->registry->getClass('class_localization')->formatNumber( $data['posts'] ) . " " . ((intval($data['_posts']) == 1) ? ("{$this->lang->words['reply']}") : ("{$this->lang->words['replies']}")) . ": {$this->lang->words['lastby']} {$data['last_poster_name']}, " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['last_post'],"SHORT", 0)) . "
							</span>
						</div>
					</div>") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- forumPasswordLogIn --*/
function forumPasswordLogIn($fid="") {
$IPBHTML = "";
$IPBHTML .= "<div class='master_list'>
	<div class='message'>{$this->lang->words['need_password_txt']}</div>
	
	<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$fid}", "public",'' ), "", "" ) . "\" method=\"post\">
		<input type=\"hidden\" name=\"L\" value=\"1\" />
	
		<h2>{$this->lang->words['need_password']}</h2>
		<div class='row'>
			{$this->lang->words['enter_forum_pass']}<br />
			<input type=\"password\" size=\"30\" name=\"f_password\" id='forum_pass' class='input_text' />
		</div>
		<div class='submit'>
			<input type=\"submit\" value=\"{$this->lang->words['f_pass_submit']}\" class=\"input_submit\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", "public",'' ), "", "" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
		</div>
	</form>
</div>";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_6c918b331dc7e992eff34bf5029dde15 = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_6c918b331dc7e992eff34bf5029dde15]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_6c918b331dc7e992eff34bf5029dde15]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_6c918b331dc7e992eff34bf5029dde15]['opts'] = $opts;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- show_rules --*/
function show_rules($rules="") {
$IPBHTML = "";
$IPBHTML .= "<h2>{$rules['title']}</h2>
<div class='general_box'>
	<h3>{$this->lang->words['forum_rules']}</h3>
	<p><br />{$rules['body']}</p>
</div>
<fieldset class='submit'>
	<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$rules['fid']}", "public",'' ), "{$rules['fseo']}", "showforum" ) . "\">{$this->lang->words['back_to_forum']}</a>
</fieldset>";
return $IPBHTML;
}

/* -- topic --*/
function topic($data, $forum_data, $other_data, $inforum) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topic'] ) )
{
$count_b7d4703fdafe3e8a78cbb56c51a03ac0 = is_array($this->functionData['topic']) ? count($this->functionData['topic']) : 0;
$this->functionData['topic'][$count_b7d4703fdafe3e8a78cbb56c51a03ac0]['data'] = $data;
$this->functionData['topic'][$count_b7d4703fdafe3e8a78cbb56c51a03ac0]['forum_data'] = $forum_data;
$this->functionData['topic'][$count_b7d4703fdafe3e8a78cbb56c51a03ac0]['other_data'] = $other_data;
$this->functionData['topic'][$count_b7d4703fdafe3e8a78cbb56c51a03ac0]['inforum'] = $inforum;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- topic_rating_image --*/
function topic_rating_image($rating_id=1) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topic_rating_image'] ) )
{
$count_a20ed8c0ba2c3a79ada6d9876fdd4ab8 = is_array($this->functionData['topic_rating_image']) ? count($this->functionData['topic_rating_image']) : 0;
$this->functionData['topic_rating_image'][$count_a20ed8c0ba2c3a79ada6d9876fdd4ab8]['rating_id'] = $rating_id;
}
$IPBHTML .= "<span class='mini_rate'>".$this->__f__f676dad3277efdc87425f1f30dc17aa1($rating_id)."</span>";
return $IPBHTML;
}


function __f__f676dad3277efdc87425f1f30dc17aa1($rating_id=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array(1,2,3,4,5) as $int )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($rating_id >= $int) ? ("
		" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "
	") : ("
		" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "
	")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicPrefixWrap --*/
function topicPrefixWrap($text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topicPrefixWrap'] ) )
{
$count_1be7e0b83a2783350fe385a2332481ba = is_array($this->functionData['topicPrefixWrap']) ? count($this->functionData['topicPrefixWrap']) : 0;
$this->functionData['topicPrefixWrap'][$count_1be7e0b83a2783350fe385a2332481ba]['text'] = $text;
}
$IPBHTML .= "" . (($text) ? ("
	<span class='topic_prefix'>{$text}</span>&nbsp;
") : ("")) . "";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>