<!doctype html>
<html lang="en">
<head>
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
	<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-glyphicons.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
	<noscript>
		<link href="/css/jquery.fileupload-ui-noscript.css" rel="stylesheet" type="text/css" />
	</noscript>
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<!--[if IE]>
		<link href="/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="/js/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	
	<script src="/js/head.load.js" type="text/javascript"></script>
	<script type="text/javascript">
		head.js(
			"/js/jquery.min.js",
			"/js/bootstrap.min.js"
			);
	</script>

	<title>acrossti.me</title>
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" id="navbar-brand" href="#">acrossti.me</a>
			<div class="nav-collapse collapse">
				<ul class="nav navbar-nav">
					<li class=""><a href="#about">timeline</a></li>
					<li class=""><a href="#contact">upload</a></li>
				</ul>
			</div><!--/.nav-collapse -->
			<div class="pull-right">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<span class="glyphicon glyphicon-asterisk"></span> <span class="caret"></span>
						</a>
						<ul class="dropdown-menu signin-dropdown" role="menu" aria-labelledby="dropdownMenu">
							<li class="signin-form">
								<form action="/forums/index.php?app=core&module=global&section=login&do=process" method="post">
									<input type="hidden" name="auth_key" value="880ea6a14ea49e853634fbdc5015a024" />
									<input type="hidden" name="referer" value="" />
									<fieldset>
										<label>
											<span>username</span>
											<input type="text" name="ips_username" class="form-control" />
										</label>
										<label>
											<span>password</span>
											<input type="password" name="ips_password" class="form-control" />
										</label>
									</fieldset>
									<fieldset class="subchk">
										<label>
											<input type="checkbox" value="1" checked="checked" name="rememberMe" />
											<span>remember me</span>
										</label>
										<label>
											<input type="checkbox" value="1" name="anonymous" />
											<span>anonymous</span>
										</label>
										<button type="submit" class="btn btn-default">sign in <span class="glyphicon glyphicon-circle-arrow-right"></span></button>
									</fieldset>
								</form>
								<p class="footer-links">
									<a href="/forums/index.php?app=core&module=global&section=lostpass"><span class="glyphicon glyphicon-question-sign"></span> forgot password</a>
									<br />
									<a href="/forums/index.php?app=core&module=global&section=register"><span class="glyphicon glyphicon-cog"></span> register</a>
								</p>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="container">
		
		<? $this->yieldView(); //The view is rendered here ?>
		
		<div id="footer" class="panel">
		<p>acrossti.me &copy; 2013</p>
		</div>
	</div>
</body>
</html>