<!doctype html>
<html lang="en">
<head>
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
	<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-image-gallery.min.css" rel="stylesheet" type="text/css" />
	<link href="/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
	<noscript>
		<link href="/css/jquery.fileupload-ui-noscript.css" rel="stylesheet" type="text/css" />
	</noscript>
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<!--[if IE]>
		<link href="/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="/js/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	
	<script src="/js/head.load.js" type="text/javascript"></script>
	<script type="text/javascript">
		head.js(
			"/js/jquery.min.js",
			"/js/bootstrap.min.js"
			);
	</script>

	<title>acrossti.me</title>
</head>

<body>
	<div class="container">
		<div id="header">
			<div class="navbar">
				<a class="navbar-brand" href="/">acrossti.me</a>
				<ul class="nav navbar-nav">
					<li class="active"><a href="/upload">Upload</a></li>
					<li><a href="/timeline">Timeline</a></li>
				</ul>
			</div>
		</div>
		
		
		<div id="main" class="panel">
		<? $this->yieldView(); //The view is rendered here ?>
		</div>
		
		<div id="footer" class="panel">
		<p>acrossti.me &copy; 2013</p>
		</div>
	</div>
</body>
</html>