<!doctype html>
<html lang="en" xmlns:ng="http://angularjs.org">
<head>
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
	<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="shortcut icon" href='/favicon.ico' />

	
	<link href="/css/smoothness/jquery-ui.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/smoothness/jquery.ui.theme.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/jquery.countdown.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
	<noscript>
		<link href="/css/jquery.fileupload-ui-noscript.css" rel="stylesheet" type="text/css" />
	</noscript>
	
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<!--[if IE]>
		<link href="/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="/js/html5shiv.js" type="text/javascript"></script>
	<![endif]-->
	
	
	
	<link href="/css/acrosstime.css" media="screen" rel="stylesheet" type="text/css" />
	
	<script src="/js/head.load.js" type="text/javascript"></script>
	<script type="text/javascript">
	<? foreach ($this->js->to_array() as $scripts): 
		$seq = array();
		array_walk($scripts, function($script, $i) use (&$seq) {
			$seq[] = '"/js/' . $script .'.js"';

		}); ?>

		head.js(<?= implode(",\n\t\t" , $seq) ?>);
	<? endforeach; ?>

	</script>

	<title>acrossti.me<? if (isset($this->title)): ?> | <?= $this->title ?><? endif; ?></title>
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" id="navbar-brand" href="#">acrossti.me</a>
			<div class="nav-collapse collapse">
				<ul class="nav navbar-nav">
					<li class=""><a href="timeline">timeline</a></li>
					<li class=""><a href="upload">upload</a></li>
				</ul>
			</div><!--/.nav-collapse -->
			<div class="pull-right">
				<ul class="nav navbar-nav">

					<? if ( !($this->ipbwi->member->isLoggedIn()) ): ?>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							sign in <span class="caret"></span>
						</a>
						<ul class="dropdown-menu signin-dropdown" role="menu" aria-labelledby="dropdownMenu">
							<li class="signin-form">
								<form action="/signin" method="post">
									<input type="hidden" name="redirect" value="<?= "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" />
									<fieldset>
										<label>
											<span>username</span>
											<input type="text" name="username" class="form-control" />
										</label>
										<label>
											<span>password</span>
											<input type="password" name="password" class="form-control" />
										</label>
									</fieldset>
									<fieldset>
										<label>
											<input type="checkbox" value="1" checked="checked" name="rememberMe" />
											<span>remember me</span>
										</label>
										<label>
											<input type="checkbox" value="1" name="anonymous" />
											<span>anonymous</span>
										</label>
										<button type="submit" class="btn btn-default">sign in <span class="glyphicon glyphicon-share-alt"></span></button>
									</fieldset>
								</form>
								<p class="footer-links">
									<a href="/forums/index.php?app=core&module=global&section=lostpass"><span class="glyphicon glyphicon-question-sign"></span> forgot password</a>
									<br />
									<a href="/forums/index.php?app=core&module=global&section=register"><span class="glyphicon glyphicon-plus"></span> register</a>
								</p>
							</li>
						</ul>
					</li>
					<? else: ?>
					<li class="dropdown">
						<? $m = $this->ipbwi->member->info(); ?>
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<?= $m['members_display_name'] ?>
						<span class="caret"></span>
						</a>
						<ul class="dropdown-menu quick-settings" role="menu" aria-labelledby="dropdownMenu">
							<li class="dropdown-header">
								WELCOME
							</li>
							<li>
								<a href="/forums/index.php?app=core&module=usercp">
									<span class="glyphicon glyphicon-cog"></span>
									my settings
								</a>
							</li>
							<li class="dropdown-header">TOOLS</li>
							<? if ($this->ipbwi->member->isAdmin()): ?>
							<li>
								<a href="/forums/admin/index.php" target="_blank">
									<span class="glyphicon glyphicon-wrench"></span>
									admin panel
								</a>
							</li>
							<? endif; ?>
							<? if ($this->ipbwi->member->isSuperMod()): ?>
							<li>
								<a href="/forums/index.php?app=core&module=modcp">
									<span class="glyphicon glyphicon-user"></span>
									moderator panel
								</a>
							</li>
							<li class="dropdown-header">ACTIONS</li>
							<li>
								<a href="/signout?redirect=<?= urlencode("http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]") ?>">
									<span class="glyphicon glyphicon-off"></span>
									sign out
								</a>
							</li>
						<? endif; ?>
						</ul>
					</li>
					<? endif; ?>
				</ul>
			</div>
		</div>
	</div>

	<div class="container">
		
		<div id="main">
			<? $this->yieldView(); //The view is rendered here ?>
		</div>

		<div id="footer" class="panel">
			<div class="panel-body">
				<p>acrossti.me &copy; 2013</p>
			</div>
		</div>
	</div>
</body>
</html>