<h1>Logging a Task</h1>

<p>We accept two date-time formats, and we're working on accepting more. Here's how it works:</p>

<table>
	<tr>
		<th>Start</th>
		<th>End</th>
		<th>Total</th>
		<th>Comments</th>
	</tr>
	<tr>
		<td>01/04/2014 8:25 pm</td>
		<td>01/04/2014 9:25 pm</td>
		<td>1 hour</td>
		<td>Most unambigious format.</td>
	</tr>
	<tr>
		<td>5:25 pm</td>
		<td>6:47 pm</td>
		<td>1 hour, 22 min</td>
		<td>Most unambigious format.</td>
	</tr>
</table>