<!-- Timer & Timeline -->

<div class="row">
	<div class="col-lg-4">
		<ul class="nav nav-tabs" id="tasknav">
			<li class="active"><a href="#logtask" data-toggle="tab">Log Task</a></li>
		</ul>
	</div>
	<div class="col-lg-8">
		<div style="height: 44px">
			&nbsp;
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4" style="margin-top: 15px">
	
		<div class="panel panel-nav">
			<div class="panel-body">
			
				<div class="tab-content">

					<!-- Log tasks completed AFK -->
					<div class="tab-pane active" id="logtask">

						<form id="recordtask" action="/upload" method="post" role="form">
							<div class="form-group">
								<input id="task" name="task" type="text" class="form-control" placeholder="Whatchu worked on?" />
							</div>
							<div class="form-group">
								<textarea class="form-control vert" rows="3" placeholder="What did you get done?" ></textarea>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-success btn-block">
									Submit
								</button>
							</div>	
								
								<!-- TODO: Image upload -->
								<!-- TODO: Time Spent -->
								<!-- TODO: Date Picker -->

						</form>

					</div>
					
					
				</div><!-- /.tab-content -->
				
			</div><!--/.panel-body-->
		</div><!-- /.panel-nav -->
		
	</div><!-- /.col-lg-4 -->
	
	<!-- TODO: Graphical representation of user's timeline -->
	<div class="col-lg-8">
		<div class="panel">
				<div class="panel-body">
					<p class="text-success">TODO: Graphical representation of user's timeline</p>
				</div>
		</div>
	</div>
	
</div><!-- /.row -->

<div class="row">

	<!-- Timeline, retrieved from Database -->
	<div class="col-xs-12">

		
			<!-- Loading, displayed while retrieving timeline -->
			<div id="loading-timeline" class="panel">
				<div class="panel-body">
					<p><img src="img/preloader.gif" alt="Preloader"/> Loading collections...</p>
				</div>
			</div>
		
			<!-- Filled with isotope of timeline stuff -->
			<div id="timeline">
				
			</div>
			
			

	</div><!-- /.col-lg-8 & TimelineCtrl -->
	
</div> <!-- /.row -->	
