<!-- Timer & Timeline -->

<div class="row">
	<div class="col-lg-4">
		<ul class="nav nav-tabs" id="tasknav">
			<li class="active"><a href="#logtask" data-toggle="tab">Log Task</a></li>
		</ul>
	</div>

</div>

<div class="row">
	<div class="col-lg-4">
	
		<div class="panel panel-nav">
			<div class="panel-body">
			
				<div class="tab-content">

					<!-- Log tasks completed AFK -->
					<div class="tab-pane active" id="logtask">

						<form id="recordtask" role="form" class="form-horizontal">
							<div class="form-group">
								<div class="col-xs-12">
									<!-- TODO: Project tracking -- http://jqueryui.com/autocomplete/ -->
									<label class="sr-only" for="title">Task Title</label>
									<input id="title" name="title" type="text" class="form-control" placeholder="Task or Project" />
								</div>
							</div>
							<div class="form-group">
								<div class="col-xs-12">
									<label class="sr-only" for="description">Task Description</label>
									<textarea id="description" name="description" class="form-control vert" rows="3" placeholder="Description (Optional)" ></textarea>
								</div>
							</div>
							
							<!-- Time Fields -->
							<div class="form-group">
								<label class="control-label col-xs-2" for="time_start">Start</label>
								<div class="col-xs-10">
									<div class="input-group">
										<input id="time_start" name="time_start" type="text" class="form-control" placeholder="MM/DD/YY h:mm a" />
										<span class="input-group-btn">
											<button class="btn btn-default" type="button" id="time_start_now">Now</button>
										</span>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-xs-2" for="time_end">Finish</label>
								<div class="col-xs-10">
									<div class="input-group">
										<input id="time_end" name="time_end" type="text" class="col-xs-6 form-control" placeholder="MM/DD/YY h:mm a" />
										<span class="input-group-btn">
											<button class="btn btn-default" type="button" id="time_end_now">Now</button>
										</span>
									</div>
								</div>
							</div>
							
							<!-- Time Spent -->
							<div class="form-group">
								<label class="control-label col-xs-2">Total</label>
								<div class="col-xs-10">
									<!-- TODO: Make this help page, add route -->
									<a href="/help/posting" class="pull-right fancybox">
										<img src="/img/icon-help.png" />
									</a>
									<p id="total" class="form-control-static">Need help with formatting time?</p>
								</div>
							</div>
							
							<!-- TODO: Image upload -->
							
							<!-- TODO: Privacy level -->
							<!-- TODO: Options - default privacy level for user's posts -->
							<!-- TODO: Options - default privacy level for each project -->
							<!-- TODO: Multiple select w/ icons? -->
							<!-- TODO: When groups is checked, add another box where you can select which groups -->
							<div class="form-group">
								<div class="col-xs-12">
									<select class="form-control" id="privacy" name="privacy">
										<option value="5">Everyone</option>
										<option value="4">Friends</option>
										<option value="3">Group(s)</option>
										<option value="2">Collaborator(s)</option>
										<option value="1">Only Me</option>
									</select>
								</div>
							</div>
							
							<div class="form-group">
								<div class="col-xs-12">
									<button type="submit" class="btn btn-success btn-block">
										Submit
									</button>
								</div>
							</div>
							
							<div id="error">
							</div>

							
								<!-- TODO: Image upload -->
								<!-- TODO: Time Spent -->
								<!-- TODO: Date Picker -->

						</form>

					</div>
					
					
				</div><!-- /.tab-content -->
				
			</div><!--/.panel-body-->
		</div><!-- /.panel-nav -->
		<div class="panel">
			<div class="panel-body">
				<p class="text-success">TODO: Graphical analysis of user's timeline</p>
			</div>
		</div>
		<div class="panel">
			<div class="panel-body">
				<p class="text-success">TODO: Friends panel</p>
			</div>
		</div>
		<div class="panel">
			<div class="panel-body">
				<p class="text-success">TODO: Groups panel</p>
			</div>
		</div>
	</div><!-- /.col-lg-4 -->
	
	
	<div class="col-lg-8">
		
		<div class="panel">
			<div class="panel-body">
				<ul id="options">
					<!-- Loading, displayed while retrieving timeline -->
					<li><img src="/img/preloader.gif" alt="Preloader" class="loader"/></li>
					<li>Sorting, filtering, search, etc.</li>
					
					<!-- TODO: Options for sorting the timeline... -->
						<!-- TODO: List view -->
						<!-- TODO: Isotope masonry view; offer several different widths? -->
					<!-- TODO: Save user preferences / set defaults -->
					<!-- TODO: Calendar view -->
					<!-- TODO: Schedule time blocks head of time? Appointments, job schedule, classes -->
					<!-- TODO: Search function (including the currently not-displayed items -->
					<!-- TODO: Infinite scroll -->
					<!-- TODO: Smart labelings of where you are in time as you're scrolling... Today, Yesterday, This Week, This Month, Per Month? -->
					
				</ul>
			</div>
		</div>
	
		<!-- Filled with isotope of timeline stuff -->
		<div id="timeline">
			
		</div>
	</div>
	
</div><!-- /.row -->

<div class="row">

	<!-- Timeline, retrieved from Database -->
	<div class="col-xs-12">



	</div><!-- /.col-lg-8 & TimelineCtrl -->
	
</div> <!-- /.row -->	
