<!-- Timer & Timeline -->

<div class="row">
	<div class="col-lg-4">
		<ul class="nav nav-tabs" id="tasknav">
			<li class="active"><a href="#logtask" data-toggle="tab">Log Task</a></li>
		</ul>
	</div>

</div>

<div class="row">
	<div class="col-lg-4">
	
		<div class="panel panel-nav">
			<div class="panel-body">
			
				<div class="tab-content">

					<!-- Log tasks completed AFK -->
					<div class="tab-pane active" id="logtask">

						<form id="recordtask" role="form" class="form-horizontal">
							<input type="hidden" id="user" name="user" value="" />
							<div class="form-group">
								<div class="col-xs-12">
									<input id="task" name="task" type="text" class="form-control" placeholder="Whatchu worked on?" />
								</div>
							</div>
							<div class="form-group">
								<div class="col-xs-12">
									<textarea id="description" name="description" class="form-control vert" rows="3" placeholder="What did you get done?" ></textarea>
								</div>
							</div>
							<!--
							<div class="form-group">
								<div class="col-xs-12">
										<label class="control-label">
											<input type="checkbox"> Enable date entry
										</label>
								</div>
							</div>
							-->
							<div class="form-group">
								<label class="control-label col-xs-2">Start</label>
								<div class="col-xs-10">
									<input id="start" name="start" type="text" class="form-control" placeholder="e.g. 12/20/13 12:00 pm" />
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-xs-2">Finish</label>
								<div class="col-xs-10">
									<input id="end" name="end" type="text" class="col-xs-6 form-control" placeholder="e.g. 12/20/13 3:00 pm" />
								</div>
							</div>
							<div class="form-group">
								<div class="col-xs-12">
									<button type="submit" class="btn btn-success btn-block">
										Submit
									</button>
								</div>
							</div>
								
								<!-- TODO: Image upload -->
								<!-- TODO: Time Spent -->
								<!-- TODO: Date Picker -->

						</form>

					</div>
					
					
				</div><!-- /.tab-content -->
				
			</div><!--/.panel-body-->
		</div><!-- /.panel-nav -->
		
	</div><!-- /.col-lg-4 -->
	
	<!-- TODO: Graphical representation of user's timeline -->
	<div class="col-lg-8">
		<div class="panel">
				<div class="panel-body">
					<p class="text-success">TODO: Graphical representation of user's timeline</p>
				</div>
		</div>
	</div>
	
</div><!-- /.row -->

<div class="row">

	<!-- Timeline, retrieved from Database -->
	<div class="col-xs-12">

		<!-- Loading, displayed while retrieving timeline -->
		<div id="loading-timeline" class="panel">
			<div class="panel-body">
				<p><img src="/img/preloader.gif" alt="Preloader"/> Loading timeline...</p>
			</div>
		</div>
	
		<!-- Filled with isotope of timeline stuff -->
		<div id="timeline">
			
		</div>

	</div><!-- /.col-lg-8 & TimelineCtrl -->
	
</div> <!-- /.row -->	
