<!doctype html>
<html lang="en">
<head>
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
	<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/css/bootstrap-image-gallery.min.css" rel="stylesheet" type="text/css" />
	<link href="/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
	<noscript>
		<link href="/css/jquery.fileupload-ui-noscript.css" rel="stylesheet" type="text/css" />
	</noscript>
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<!--[if IE]>
		<link href="/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="/js/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	
	<script src="/js/head.load.js" type="text/javascript"></script>
	<script type="text/javascript">
		head.js(
			"/js/jquery.min.js",
			"/js/angular.min.js",
			"/js/vendor/jquery.ui.widget.js",
			"/js/load-image.min.js",
			"/js/canvas-to-blob.min.js",
			"/js/jquery.iframe-transport.js",
			"/js/jquery.fileupload.js",
			"/js/jquery.fileupload-process.js",
			"/js/jquery.fileupload-image.js",
			"/js/jquery.fileupload-audio.js",
			"/js/jquery.fileupload-video.js",
			"/js/jquery.fileupload-validate.js",
			"/js/jquery.fileupload-angular.js",
			"/js/app.js"
			);
		head.js(
			"/js/bootstrap.min.js",
			"/js/bootstrap-image-gallery.min.js"
			);
	</script>
	

	<? /*
	<!-- jQuery -->
	<script src="/js/jquery.min.js"></script>
	<!-- angularjs -->
	<script src="/js/angular.min.js"></script>
	<!-- jQuery UI -->
	<script src="/js/vendor/jquery.ui.widget.js"></script>
	<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
	<script src="/js/load-image.min.js"></script>
	<!-- The Canvas to Blob plugin is included for image resizing functionality -->
	<script src="/js/canvas-to-blob.min.js"></script>
	<!-- Bootstrap JS and Bootstrap Image Gallery are not required, but included for the demo -->
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/bootstrap-image-gallery.min.js"></script>
	<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
	<script src="/js/jquery.iframe-transport.js"></script>
	<!-- The basic File Upload plugin -->
	<script src="/js/jquery.fileupload.js"></script>
	<!-- The File Upload processing plugin -->
	<script src="/js/jquery.fileupload-process.js"></script>
	<!-- The File Upload image preview & resize plugin -->
	<script src="/js/jquery.fileupload-image.js"></script>
	<!-- The File Upload audio preview plugin -->
	<script src="/js/jquery.fileupload-audio.js"></script>
	<!-- The File Upload video preview plugin -->
	<script src="/js/jquery.fileupload-video.js"></script>
	<!-- The File Upload validation plugin -->
	<script src="/js/jquery.fileupload-validate.js"></script>
	<!-- The File Upload Angular JS module -->
	<script src="/js/jquery.fileupload-angular.js"></script>
	<!-- The main application script -->
	<script src="/js/app.js"></script>
	*/ ?>

	<title>acrossti.me</title>
</head>

<body>
	<div class="container">
		<div id="header">
			<div class="navbar">
				<a class="navbar-brand" href="/">Across Time</a>
				<ul class="nav navbar-nav">
					<li class="active"><a href="/upload">Upload</a></li>
					<li><a href="/timeline">Timeline</a></li>
				</ul>
			</div>
		</div>
		
		
		<div id="main" class="panel">
		<?php $this->yieldView(); //The view is rendered here ?>
		</div>
		
		<div id="footer" class="panel">
		<p>AcrossTime &copy; 2013 - Blah - Bleh - Bloop</p>
		</div>
	</div>
</body>
</html>