<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 11 Jun 2013 11:12:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_register_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['completePartialLogin'] = array('reqCfieldDescSpan','custom_required','optCfieldDescSpan','custom_optional','hasAName','partialLoginErrors','fbDNInner','fbDisplayName','partialAllowDnames','partialNoEmail','reqCfields','optCfields','partialCustomFields','reqCfieldDesc','reqCfieldDescSpan','custom_required','optCfieldDesc','optCfieldDescSpan','custom_optional','partialLoginErrors','partialAllowDnames','partialNoEmail','reqCfields','optCfields','partialCustomFields');
$this->_funcHooks['lostPasswordForm'] = array('lostPasswordErrors','lostPasswordErrors');
$this->_funcHooks['registerCoppaForm'] = array('coppaConsentExtra','coppaConsentExtra');
$this->_funcHooks['registerCoppaStart'] = array('coppaMRange','coppaDRange','coppaYRange','useCoppa');
$this->_funcHooks['registerForm'] = array('general_errors','statesJs','isCountrySelect','isCountryWords','options','states','statesCountries','isAddressOrPhone','isAddress2','isAddress1','textRequired','textErrorMessage','isText','dropdownRequired','isCountry','dropdownErrorMessage','isDropdown','specialRequired','specialErrorMessage','isSpecial','fields','reqCfieldDescSpan','custom_required','optCfieldDescSpan','custom_optional','registerHasErrors','registerUsingFb','twitterBox','registerServices','registerHasInlineErrors','ieDnameClass','ieDname','ieEmailClass','ieEmail','iePasswordClass','iePassword','hasNexusFields','reqCfields','optCfields','hasCfields','defaultAAE','checkedTOS','ieDnameClass','ieTOS','privvy','general_errors','reqCfieldDescSpan','custom_required','optCfieldDescSpan','custom_optional','registerHasErrors','ieDname','ieDname','ieEmail','ieEmail','iePassword','iePassword','reqCfields','optCfields','hasCfields','defaultAAE','useCoppa');
$this->_funcHooks['showLostpassForm'] = array('lostpassFormErrors','lpFormMethodChoose','lostpassFormErrors','lpFormMethodChoose');
$this->_funcHooks['showRevalidateForm'] = array('revalidateError','revalidateError');


}

/* -- completePartialLogin --*/
function completePartialLogin($mid="",$key="",$custom_fields="",$errors="", $reg="", $userFromService=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['completePartialLogin'] ) )
{
$count_01e74e03fbd0d83993f6605eb28d3414 = is_array($this->functionData['completePartialLogin']) ? count($this->functionData['completePartialLogin']) : 0;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['mid'] = $mid;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['key'] = $key;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['custom_fields'] = $custom_fields;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['errors'] = $errors;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['reg'] = $reg;
$this->functionData['completePartialLogin'][$count_01e74e03fbd0d83993f6605eb28d3414]['userFromService'] = $userFromService;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- lostPasswordForm --*/
function lostPasswordForm($errors="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['lostPasswordForm'] ) )
{
$count_67855697121d6d2864855fba982d45a5 = is_array($this->functionData['lostPasswordForm']) ? count($this->functionData['lostPasswordForm']) : 0;
$this->functionData['lostPasswordForm'][$count_67855697121d6d2864855fba982d45a5]['errors'] = $errors;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- lostPasswordWait --*/
function lostPasswordWait($member="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- registerCoppaForm --*/
function registerCoppaForm() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['registerCoppaForm'] ) )
{
$count_189e60187e66bb2614060fdcb37d6ed6 = is_array($this->functionData['registerCoppaForm']) ? count($this->functionData['registerCoppaForm']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- registerCoppaStart --*/
function registerCoppaStart() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['registerCoppaStart'] ) )
{
$count_04d15105a507146c648bcdf758ba19c9 = is_array($this->functionData['registerCoppaStart']) ? count($this->functionData['registerCoppaStart']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- registerCoppaTwo --*/
function registerCoppaTwo() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- registerForm --*/
function registerForm($general_errors=array(), $data=array(), $inline_errors=array(), $time_select=array(), $custom_fields=array(), $nexusFields=array(), $nexusStates=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['registerForm'] ) )
{
$count_151df0c65d01b53966ff1a47cfedadbc = is_array($this->functionData['registerForm']) ? count($this->functionData['registerForm']) : 0;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['general_errors'] = $general_errors;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['data'] = $data;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['inline_errors'] = $inline_errors;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['time_select'] = $time_select;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['custom_fields'] = $custom_fields;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['nexusFields'] = $nexusFields;
$this->functionData['registerForm'][$count_151df0c65d01b53966ff1a47cfedadbc]['nexusStates'] = $nexusStates;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- registerStepBar --*/
function registerStepBar($step) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- show_lostpass_form_auto --*/
function show_lostpass_form_auto($aid="",$uid="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- show_lostpass_form_manual --*/
function show_lostpass_form_manual() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showAuthorize --*/
function showAuthorize($member="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showLostpassForm --*/
function showLostpassForm($error) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['showLostpassForm'] ) )
{
$count_df6701fe770d2c21d15dcb5c75b9b670 = is_array($this->functionData['showLostpassForm']) ? count($this->functionData['showLostpassForm']) : 0;
$this->functionData['showLostpassForm'][$count_df6701fe770d2c21d15dcb5c75b9b670]['error'] = $error;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showLostPassWaitRandom --*/
function showLostPassWaitRandom($member="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showManualForm --*/
function showManualForm($type="reg") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showPreview --*/
function showPreview($member="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showRevalidated --*/
function showRevalidated() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showRevalidateForm --*/
function showRevalidateForm($name="",$error="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_register', $this->_funcHooks['showRevalidateForm'] ) )
{
$count_126124211430edbc93742962783224a5 = is_array($this->functionData['showRevalidateForm']) ? count($this->functionData['showRevalidateForm']) : 0;
$this->functionData['showRevalidateForm'][$count_126124211430edbc93742962783224a5]['name'] = $name;
$this->functionData['showRevalidateForm'][$count_126124211430edbc93742962783224a5]['error'] = $error;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>