<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 11 Jun 2013 11:12:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_login_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajax__inlineLogInForm'] = array('registerUsingFb','twitterBox','haswindowslive','registerServices','anonymous','hasRedirect');
$this->_funcHooks['showLogInForm'] = array('extrafields','referer','facebook','twitterBox','haswindowslive','extraform','liveform','anonymous','privvy','toggleLive','referer','haswindowslive','hasFacebook','hasTwitter','showAlternate','anonymous');


}

/* -- ajax__inlineLogInForm --*/
function ajax__inlineLogInForm() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_login', $this->_funcHooks['ajax__inlineLogInForm'] ) )
{
$count_6ac151f368494c312f5dfe4d0090a66c = is_array($this->functionData['ajax__inlineLogInForm']) ? count($this->functionData['ajax__inlineLogInForm']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- errors --*/
function errors($data="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- showLogInForm --*/
function showLogInForm($message="",$referer="",$extra_form="", $login_methods=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_login', $this->_funcHooks['showLogInForm'] ) )
{
$count_39e10914ca2abb031849559b8276cecc = is_array($this->functionData['showLogInForm']) ? count($this->functionData['showLogInForm']) : 0;
$this->functionData['showLogInForm'][$count_39e10914ca2abb031849559b8276cecc]['message'] = $message;
$this->functionData['showLogInForm'][$count_39e10914ca2abb031849559b8276cecc]['referer'] = $referer;
$this->functionData['showLogInForm'][$count_39e10914ca2abb031849559b8276cecc]['extra_form'] = $extra_form;
$this->functionData['showLogInForm'][$count_39e10914ca2abb031849559b8276cecc]['login_methods'] = $login_methods;
}
$IPBHTML .= "<template>LoginRequired</template>
<categories>
	<category>
		<id>180</id>
		<name>
		<![CDATA[ Registration Required ]]>
		</name>
		<forums>
			<forum>
				<id>1</id>
				<name>
					<![CDATA[ Please login or register ]]>
				</name>
				<url>
					<![CDATA[]]>
				</url>
				<description>
					<![CDATA[]]>
				</description>
				<isRead>1</isRead>
				<redirect>0</redirect>
				<type/>
				<topics>0</topics>
				<replies>0</replies>
				<lastpost>
					<date>14 May 2012</date>
					<name>
						<![CDATA[]]>
					</name>
					<id>362680</id>
					<url>
						<![CDATA[]]>
					</url>
					<user>
						<id>0</id>
						<name>
						<![CDATA[]]>
						</name>
						<url>
							<![CDATA[]]>
						</url>
					</user>
				</lastpost>
			</forum>
		</forums>
	</category>
</categories>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>