<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Mon, 10 Jun 2013 14:58:21 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_online_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['showOnlineList'] = array('username','userid','viewanon','anonymous','showip','wheretextseo','wheretext','detailslink','wheretextseo','enddetailslink','nomoreenddetailslink','moredetails','nowhere','addfriend','notus','sendpm','blog','gallery','options','online','defaultsort','sort_key','defaultfilter','show_mem','defaultorder','sort_order','onlineusers','userid','username','viewanon','anonymous','showip','wheretext','detailslink','wheretextseo','enddetailslink','nomoreenddetailslink','moredetails','nowhere','addfriend','notus','sendpm','blog','gallery','options','online','defaultsort','sort_key','defaultfilter','show_mem','defaultorder','sort_order','onlineusers');


}

/* -- showOnlineList --*/
function showOnlineList($rows, $links="", $defaults=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_online', $this->_funcHooks['showOnlineList'] ) )
{
$count_064d7cbe57522e5994030b0e6aa5b591 = is_array($this->functionData['showOnlineList']) ? count($this->functionData['showOnlineList']) : 0;
$this->functionData['showOnlineList'][$count_064d7cbe57522e5994030b0e6aa5b591]['rows'] = $rows;
$this->functionData['showOnlineList'][$count_064d7cbe57522e5994030b0e6aa5b591]['links'] = $links;
$this->functionData['showOnlineList'][$count_064d7cbe57522e5994030b0e6aa5b591]['defaults'] = $defaults;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>