<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 11 Jun 2013 11:12:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_other_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxPopUpNoPermission'] = array('msg','msg');
$this->_funcHooks['displayBoardOffline'] = array('isGuest','isGuest');
$this->_funcHooks['displayPopUpWindow'] = array('donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popupjsmodules','popuphttpsp','popuprl','popupjsmodules','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl','donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popuphttpsp','popuprl','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl');
$this->_funcHooks['Error'] = array('haserrorcode','savedpost','showerrortitle','haserrorcode','savedpost');
$this->_funcHooks['facebookPop'] = array('hasFbConnected');
$this->_funcHooks['generateTopicIcon'] = array('topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap','topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap');
$this->_funcHooks['globalTemplateMinimal'] = array('fbcenabled','pagenumberintitle','isLargeTouch','isSmallTouch','mainpageContent','lastvisit','isfloat','sqldebuglink','closesqldebuglink','showdebuglevel','fbcenabled','pagenumberintitle','brandingBar','messengerlink','memberbox','hasBlog','hasGallery','viewnewcontentapp','mainpageContent','skinchanger','langchooser','isNotMobbyApp');
$this->_funcHooks['inboxList'] = array('loopynotify','hasTopics');
$this->_funcHooks['likeMoreDialogue'] = array('hasVisibleEntries','hasAnonEntries');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['notificationsList'] = array('loopynotify','hasnotifications','notifications');
$this->_funcHooks['questionAndAnswer'] = array('qadefault');
$this->_funcHooks['quickNavigationPanel'] = array('depth','important','innerAgain','hasTitle','linksisarray','outer');
$this->_funcHooks['quickNavigationWrapper'] = array('active','navTabs','isLargeTouch');
$this->_funcHooks['redirectTemplate'] = array('redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink','redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink');
$this->_funcHooks['repButtons'] = array('hasNoLikes','giveRepUp','giveRepDown','canGiveRep','pos','giveRepUp','giveRepDown','canGiveRep','hasNoRep','hasPosRep','hasNegRep','isNotLike','isLike','canRep','reputationBox','giveRepUp','giveRepDown','giveRepUp','giveRepDown','canGiveRep','isLike','canRep','reputationBox','giveRepUp','canGiveRep','canGiveRep','giveRepDown','isLike','canRep');
$this->_funcHooks['socialSharePostStrip'] = array('canShareThis','services','canSave','canShare');
$this->_funcHooks['tagCloud'] = array('eachTag','eachTag');
$this->_funcHooks['tagEntry'] = array('noClass','inSearch','inSearchSub','hasSearchSection','noClass','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagPrefix'] = array('inSearch','inSearchSub','hasSearchSection','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagTextEntryBox'] = array('isClosedField','prefixChecked','canPrefix');


}

/* -- ajaxPopUpNoPermission --*/
function ajaxPopUpNoPermission($msg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['ajaxPopUpNoPermission'] ) )
{
$count_94b1392a2c681848e8b7d68f248eed70 = is_array($this->functionData['ajaxPopUpNoPermission']) ? count($this->functionData['ajaxPopUpNoPermission']) : 0;
$this->functionData['ajaxPopUpNoPermission'][$count_94b1392a2c681848e8b7d68f248eed70]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaGD --*/
function captchaGD($captcha_unique_id) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaKeycaptcha --*/
function captchaKeycaptcha($challenge="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- captchaRecaptcha --*/
function captchaRecaptcha($html="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayBoardOffline --*/
function displayBoardOffline($message="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayBoardOffline'] ) )
{
$count_3b929e4608a108cb3499ab97260f3301 = is_array($this->functionData['displayBoardOffline']) ? count($this->functionData['displayBoardOffline']) : 0;
$this->functionData['displayBoardOffline'][$count_3b929e4608a108cb3499ab97260f3301]['message'] = $message;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayPopUpWindow --*/
function displayPopUpWindow($documentHeadItems, $css, $jsLoaderItems, $title="", $output="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayPopUpWindow'] ) )
{
$count_21b60aa636f2a95f697e7db64582f324 = is_array($this->functionData['displayPopUpWindow']) ? count($this->functionData['displayPopUpWindow']) : 0;
$this->functionData['displayPopUpWindow'][$count_21b60aa636f2a95f697e7db64582f324]['documentHeadItems'] = $documentHeadItems;
$this->functionData['displayPopUpWindow'][$count_21b60aa636f2a95f697e7db64582f324]['css'] = $css;
$this->functionData['displayPopUpWindow'][$count_21b60aa636f2a95f697e7db64582f324]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['displayPopUpWindow'][$count_21b60aa636f2a95f697e7db64582f324]['title'] = $title;
$this->functionData['displayPopUpWindow'][$count_21b60aa636f2a95f697e7db64582f324]['output'] = $output;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- Error --*/
function Error($message="",$code=0,$ad_email_one="",$ad_email_two="", $title="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['Error'] ) )
{
$count_ab863611dd1c2ad926b6c9081ce7c01e = is_array($this->functionData['Error']) ? count($this->functionData['Error']) : 0;
$this->functionData['Error'][$count_ab863611dd1c2ad926b6c9081ce7c01e]['message'] = $message;
$this->functionData['Error'][$count_ab863611dd1c2ad926b6c9081ce7c01e]['code'] = $code;
$this->functionData['Error'][$count_ab863611dd1c2ad926b6c9081ce7c01e]['ad_email_one'] = $ad_email_one;
$this->functionData['Error'][$count_ab863611dd1c2ad926b6c9081ce7c01e]['ad_email_two'] = $ad_email_two;
$this->functionData['Error'][$count_ab863611dd1c2ad926b6c9081ce7c01e]['title'] = $title;
}
$IPBHTML .= "<error>{$message}</error>";
return $IPBHTML;
}

/* -- facebookDone --*/
function facebookDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- facebookPop --*/
function facebookPop($user=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['facebookPop'] ) )
{
$count_fa46715a1baa7c76e5739712c1085389 = is_array($this->functionData['facebookPop']) ? count($this->functionData['facebookPop']) : 0;
$this->functionData['facebookPop'][$count_fa46715a1baa7c76e5739712c1085389]['user'] = $user;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followUnsubscribe --*/
function followUnsubscribe($data, $meta) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- generateTopicIcon --*/
function generateTopicIcon($imgArray, $unreadUrl) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['generateTopicIcon'] ) )
{
$count_8572be0c204337e66d2426da82bf4104 = is_array($this->functionData['generateTopicIcon']) ? count($this->functionData['generateTopicIcon']) : 0;
$this->functionData['generateTopicIcon'][$count_8572be0c204337e66d2426da82bf4104]['imgArray'] = $imgArray;
$this->functionData['generateTopicIcon'][$count_8572be0c204337e66d2426da82bf4104]['unreadUrl'] = $unreadUrl;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- globalTemplateMinimal --*/
function globalTemplateMinimal($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['globalTemplateMinimal'] ) )
{
$count_f38cf42465ec9ab086d583140808a2ec = is_array($this->functionData['globalTemplateMinimal']) ? count($this->functionData['globalTemplateMinimal']) : 0;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['html'] = $html;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['documentHeadItems'] = $documentHeadItems;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['css'] = $css;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['jsModules'] = $jsModules;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['metaTags'] = $metaTags;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['header_items'] = $header_items;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['items'] = $items;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['footer_items'] = $footer_items;
$this->functionData['globalTemplateMinimal'][$count_f38cf42465ec9ab086d583140808a2ec]['stats'] = $stats;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inboxList --*/
function inboxList($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['inboxList'] ) )
{
$count_b670e69a97d554b6baeba7512c53baf0 = is_array($this->functionData['inboxList']) ? count($this->functionData['inboxList']) : 0;
$this->functionData['inboxList'][$count_b670e69a97d554b6baeba7512c53baf0]['topics'] = $topics;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineUploaderComplete --*/
function inlineUploaderComplete($json) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeMoreDialogue --*/
function likeMoreDialogue($data, $relId, $cache) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeMoreDialogue'] ) )
{
$count_90b36b93bc22c54bf84fb705624a35c4 = is_array($this->functionData['likeMoreDialogue']) ? count($this->functionData['likeMoreDialogue']) : 0;
$this->functionData['likeMoreDialogue'][$count_90b36b93bc22c54bf84fb705624a35c4]['data'] = $data;
$this->functionData['likeMoreDialogue'][$count_90b36b93bc22c54bf84fb705624a35c4]['relId'] = $relId;
$this->functionData['likeMoreDialogue'][$count_90b36b93bc22c54bf84fb705624a35c4]['cache'] = $cache;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSetDialogue --*/
function likeSetDialogue($app, $area, $relid, $data) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_c6c467a310c91d5aba56c9428c986c4f = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_c6c467a310c91d5aba56c9428c986c4f]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_c6c467a310c91d5aba56c9428c986c4f]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_c6c467a310c91d5aba56c9428c986c4f]['opts'] = $opts;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsList --*/
function notificationsList($notifications) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['notificationsList'] ) )
{
$count_41007d3eafba47bb6451cc1f399bb490 = is_array($this->functionData['notificationsList']) ? count($this->functionData['notificationsList']) : 0;
$this->functionData['notificationsList'][$count_41007d3eafba47bb6451cc1f399bb490]['notifications'] = $notifications;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__98d2398198e1dcb270d74f94b9098412($notifications)."</notifications>";
return $IPBHTML;
}


function __f__98d2398198e1dcb270d74f94b9098412($notifications)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- privacyPolicy --*/
function privacyPolicy($title, $text) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- questionAndAnswer --*/
function questionAndAnswer($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['questionAndAnswer'] ) )
{
$count_0c02ca4a6c6628fc3e1ff66a29fdc480 = is_array($this->functionData['questionAndAnswer']) ? count($this->functionData['questionAndAnswer']) : 0;
$this->functionData['questionAndAnswer'][$count_0c02ca4a6c6628fc3e1ff66a29fdc480]['data'] = $data;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationOffline --*/
function quickNavigationOffline($message) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationPanel --*/
function quickNavigationPanel($data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationPanel'] ) )
{
$count_7e9b426eb1806a670ae2e0f8f409ba3d = is_array($this->functionData['quickNavigationPanel']) ? count($this->functionData['quickNavigationPanel']) : 0;
$this->functionData['quickNavigationPanel'][$count_7e9b426eb1806a670ae2e0f8f409ba3d]['data'] = $data;
$this->functionData['quickNavigationPanel'][$count_7e9b426eb1806a670ae2e0f8f409ba3d]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationWrapper --*/
function quickNavigationWrapper($tabs=array(), $data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationWrapper'] ) )
{
$count_39d68b9b888b7260ecd04a7cf7743896 = is_array($this->functionData['quickNavigationWrapper']) ? count($this->functionData['quickNavigationWrapper']) : 0;
$this->functionData['quickNavigationWrapper'][$count_39d68b9b888b7260ecd04a7cf7743896]['tabs'] = $tabs;
$this->functionData['quickNavigationWrapper'][$count_39d68b9b888b7260ecd04a7cf7743896]['data'] = $data;
$this->functionData['quickNavigationWrapper'][$count_39d68b9b888b7260ecd04a7cf7743896]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- redirectTemplate --*/
function redirectTemplate($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['redirectTemplate'] ) )
{
$count_2aef481d5da5727635a1af6f14ef1dc8 = is_array($this->functionData['redirectTemplate']) ? count($this->functionData['redirectTemplate']) : 0;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['documentHeadItems'] = $documentHeadItems;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['css'] = $css;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['text'] = $text;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['url'] = $url;
$this->functionData['redirectTemplate'][$count_2aef481d5da5727635a1af6f14ef1dc8]['full'] = $full;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- repButtons --*/
function repButtons($member, $data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['repButtons'] ) )
{
$count_8fab0af945c9416e5f3b8442cbbeb4a8 = is_array($this->functionData['repButtons']) ? count($this->functionData['repButtons']) : 0;
$this->functionData['repButtons'][$count_8fab0af945c9416e5f3b8442cbbeb4a8]['member'] = $member;
$this->functionData['repButtons'][$count_8fab0af945c9416e5f3b8442cbbeb4a8]['data'] = $data;
}
$IPBHTML .= "" . ((!( $this->settings['reputation_protected_groups'] && in_array( $member['member_group_id'], explode( ',', $this->settings['reputation_protected_groups'] ) ) ) and $this->memberData['member_id']) ? ("" . (($this->settings['reputation_point_types'] == 'like') ? ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("" . ((IPSMember::canRepUp( $data, $member ) !== false) ? ("
				<likeURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></likeURL>
			") : ("")) . "") : ("")) . "") : ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("
			<repupURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repupURL>
		") : ("")) . "
		" . ((IPSMember::canRepDown( $data, $member ) !== false) ? ("
			<repDownURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=-1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repDownURL>
		") : ("")) . "")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- repMoreDialogue --*/
function repMoreDialogue($data, $relId) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- reputationPopup --*/
function reputationPopup($reps) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- socialSharePostStrip --*/
function socialSharePostStrip($id=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['socialSharePostStrip'] ) )
{
$count_09a8b14ec7df6fa38bd8f1e655747569 = is_array($this->functionData['socialSharePostStrip']) ? count($this->functionData['socialSharePostStrip']) : 0;
$this->functionData['socialSharePostStrip'][$count_09a8b14ec7df6fa38bd8f1e655747569]['id'] = $id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagCloud --*/
function tagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagCloud'] ) )
{
$count_daca9115d4ca3d2830cf8824d1478300 = is_array($this->functionData['tagCloud']) ? count($this->functionData['tagCloud']) : 0;
$this->functionData['tagCloud'][$count_daca9115d4ca3d2830cf8824d1478300]['tags'] = $tags;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagEntry --*/
function tagEntry($tag, $noClass=false, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagEntry'] ) )
{
$count_ae89675c73e86d9648335ce5269b349d = is_array($this->functionData['tagEntry']) ? count($this->functionData['tagEntry']) : 0;
$this->functionData['tagEntry'][$count_ae89675c73e86d9648335ce5269b349d]['tag'] = $tag;
$this->functionData['tagEntry'][$count_ae89675c73e86d9648335ce5269b349d]['noClass'] = $noClass;
$this->functionData['tagEntry'][$count_ae89675c73e86d9648335ce5269b349d]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagPrefix --*/
function tagPrefix($tag, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagPrefix'] ) )
{
$count_b3253d5021daf5dee43200c47d23e8e1 = is_array($this->functionData['tagPrefix']) ? count($this->functionData['tagPrefix']) : 0;
$this->functionData['tagPrefix'][$count_b3253d5021daf5dee43200c47d23e8e1]['tag'] = $tag;
$this->functionData['tagPrefix'][$count_b3253d5021daf5dee43200c47d23e8e1]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagsAsPopUp --*/
function tagsAsPopUp($tags) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagTextEntryBox --*/
function tagTextEntryBox($tags, $options, $where) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagTextEntryBox'] ) )
{
$count_8ef1b70f1e5cf45e223b6f6926ef4d07 = is_array($this->functionData['tagTextEntryBox']) ? count($this->functionData['tagTextEntryBox']) : 0;
$this->functionData['tagTextEntryBox'][$count_8ef1b70f1e5cf45e223b6f6926ef4d07]['tags'] = $tags;
$this->functionData['tagTextEntryBox'][$count_8ef1b70f1e5cf45e223b6f6926ef4d07]['options'] = $options;
$this->functionData['tagTextEntryBox'][$count_8ef1b70f1e5cf45e223b6f6926ef4d07]['where'] = $where;
}
$IPBHTML .= "<tagSystemIsEnabled>{$options['isEnabled']}</tagSystemIsEnabled>
<tagSystemIsOpen>{$options['isOpenSystem']}</tagSystemIsOpen>
<prefixesEnabled>{$options['prefixesEnabled']}</prefixesEnabled>
<predefinedTags>
</predefinedTags>";
return $IPBHTML;
}

/* -- twitterDone --*/
function twitterDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- twitterPop --*/
function twitterPop($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>