<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 10 Jun 2013 14:56:27 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'bad_email_password' => "Your login credentials were not valid",
'enter_name_and_email' => "Username / Email",
'enter_useremail' => "Email Address",
'enter_username' => "Username",
'ipb_login' => "IP.Board: Log in",
'logout_complete' => "Log out complete",
'no_acp_access' => "You do not have permission to access the ACP",
 ); 
