<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 11 Jun 2013 11:11:15 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'forum_leaders' => "The moderating team",
'go_button' => "Go",
'goto_profile' => "Go to profile",
'leader_all_forums' => "All Forums",
'leader_forums' => "Forums",
'leader_group' => "Group",
'leader_last_seen' => "Last Active",
'leader_name' => "Member Name",
'm_online' => "Online",
'member' => "Member",
'member_joined' => "Joined",
'member_percent' => "% of today's posts",
'member_posts' => "Total Member Posts",
'member_today' => "Posts Today",
'no_forums' => "View %s Forums",
'no_info' => "No information is available at this time",
'notopic_attach' => "Could not load attachments for the requested topic",
'stats_missing_tid' => "You must select a valid topic for this feature",
'todays_posters' => "Today's Top 20 Posters",
'top_poster_title' => "Today's top 20 posters",
'topic_noattach' => "The specified topic does not have any attachments",
'topic_noperms' => "You do not have permission to access this forum",
'who_farted' => "Who posted in:",
'who_replied_title' => "Who posted in this topic",
'whoposted_name' => "Member name",
'whoposted_posts' => "Posts",
 ); 
